import fs from 'node:fs';
const bots=JSON.parse(fs.readFileSync('data/manifest.json')).bots;
const escape=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
// The home page, /chat/ directory, /learn/ pages and sitemap are generated by scripts/build-site.mjs.
// This script only refreshes the per-assistant topic buttons.
for(const bot of bots){
 const {KB}=await import(new URL('../../data/bots/'+bot.id+'/knowledge.js',import.meta.url));
 const topics=KB.map(e=>`<button type="button" data-question="${escape('Explain '+e.name)}">${escape(e.name)}</button>`).join('');
 const path='chat/'+bot.id+'/index.html';let html=fs.readFileSync(path,'utf8');
 html=html.replace(/<div id="topic-list">[\s\S]*?<\/div>/,`<div id="topic-list">${topics}</div>`);
 html=html.replace(/<summary>Browse.*?<\/summary>/,`<summary>Browse ${KB.length} topics and sources</summary>`);
 fs.writeFileSync(path,html);
}
