import fs from 'node:fs';
const bots=JSON.parse(fs.readFileSync('data/manifest.json')).bots;
const escape=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cards=bots.map((b,i)=>`<a class="catalog-card" href="${b.url}"><span class="catalog-number">0${i+1} · ${b.topic_count} topics${i>2?' · New':''}</span><h3>${escape(b.name)}</h3><p>${escape(b.description)}</p><span class="catalog-action">Open chat <span aria-hidden="true">↗</span></span></a>`).join('\n');
const section=`<section class="bot-catalog" id="chatbots" aria-labelledby="catalog-title"><div class="catalog-heading"><div><p class="eyebrow">Pick a subject</p><h2 id="catalog-title">What are you curious about?</h2></div><p>Six focused assistants. Examples, explanations, and follow-up questions. Free to use.</p></div><div class="catalog-grid">${cards}</div></section>`;
let home=fs.readFileSync('index.html','utf8');
if(home.includes('<!-- START BOT CATALOG -->')) home=home.replace(/<!-- START BOT CATALOG -->[\s\S]*?<!-- END BOT CATALOG -->/,'<!-- START BOT CATALOG -->'+section+'<!-- END BOT CATALOG -->');
else home=home.replace('<!-- ==================== EBOOK BANNER ==================== -->','<!-- START BOT CATALOG -->'+section+'<!-- END BOT CATALOG -->\n<!-- ==================== EBOOK BANNER ==================== -->');
if(!home.includes('/assets/css/catalog.css'))home=home.replace('</head>','<link rel="stylesheet" href="/assets/css/catalog.css?v=14">\n</head>');
fs.writeFileSync('index.html',home);
const schema={'@context':'https://schema.org','@type':'CollectionPage',name:'Free private learning chatbots',url:'https://relu.chat/chat/',description:'Six browser-based learning assistants for mathematics, science, history, and web development.',mainEntity:{'@type':'ItemList',itemListElement:bots.map((b,i)=>({'@type':'ListItem',position:i+1,name:b.name,url:'https://relu.chat'+b.url}))}};
fs.writeFileSync('chat/index.html',`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>6 Free Private Learning Chatbots — ReLU.chat</title><meta name="description" content="Explore game theory, data science, history, reinforcement learning, linear algebra, and web development with six free chatbots that run in your browser."><link rel="canonical" href="https://relu.chat/chat/"><meta property="og:title" content="Choose your learning chatbot — ReLU.chat"><meta property="og:description" content="Six subjects. Clear explanations. Your conversation stays in your browser."><meta property="og:url" content="https://relu.chat/chat/"><meta property="og:type" content="website"><meta property="og:image" content="https://relu.chat/assets/logo.png"><link rel="icon" href="/assets/logo.png"><link rel="stylesheet" href="/assets/fonts/sora.css"><link rel="stylesheet" href="/assets/shared-design.css?v=14"><link rel="stylesheet" href="/assets/css/catalog.css?v=14"><script type="application/ld+json">${JSON.stringify(schema)}</script></head><body class="catalog-page"><a class="skip-link" href="#main-content">Skip to chatbots</a><nav class="site-nav" aria-label="Primary navigation"><div class="nav-container"><a class="nav-logo" href="/"><img src="/assets/logo.png" alt="" width="28" height="28">ReLU.chat</a><a href="/blog/">Learning guides</a><a href="/tools/">Interactive tools</a></div></nav><main id="main-content"><header class="directory-intro"><p class="eyebrow">Learn at your own pace</p><h1>One question can open<br>a whole new subject.</h1><p>Start with a definition. Ask for an example. Follow your curiosity.<br>Your questions and answers are processed on your device.</p></header>${section}<section class="catalog-notes"><h2>What to expect</h2><p>These assistants explain concepts from curated knowledge bases. They do not browse the live web, run your code, or solve every exercise. They can misunderstand a question. Source links and our learning guides help you check the details.</p><p>Start immediately with keyword matching. Enhanced matching downloads a model of about 22 MB when you choose it, then caches it in your browser. Offline access depends on which pages and assets you have already loaded.</p><a href="/how-it-works.html">See how ReLU.chat works →</a></section></main><footer class="catalog-footer"><a href="/">ReLU.chat</a> · <a href="/blog/">Blog</a> · <a href="https://github.com/yunusemrejr/relu-chat">Open source</a></footer></body></html>`);
for(const bot of bots){
 const {KB}=await import(new URL('../../data/bots/'+bot.id+'/knowledge.js',import.meta.url));
 const topics=KB.map(e=>`<button type="button" data-question="${escape('Explain '+e.name)}">${escape(e.name)}</button>`).join('');
 const path='chat/'+bot.id+'/index.html';let html=fs.readFileSync(path,'utf8');
 html=html.replace(/<div id="topic-list">[\s\S]*?<\/div>/,`<div id="topic-list">${topics}</div>`);
 html=html.replace(/<summary>Browse.*?<\/summary>/,`<summary>Browse ${KB.length} topics and sources</summary>`);
 fs.writeFileSync(path,html);
}
