export function kb(id, name, aliases, summary, f) {
  return { id, name, aliases: [name.toLowerCase(), ...aliases.map(a => a.toLowerCase())], summary, f };
}

export const KB = [
  kb('nash_eq','Nash Equilibrium',['nash','ne'],
    'A profile of strategies where no player can profit by unilateral deviation.',{
    def:['A strategy profile $s^*=(s_1^*,\\ldots,s_n^*)$ is a Nash equilibrium if $u_i(s_i^*,s_{-i}^*)\\ge u_i(s_i,s_{-i}^*)$ for every player $i$ and every $s_i\\in S_i$.',
         'Equivalently, $s_i^*\\in\\arg\\max_{s_i\\in S_i} u_i(s_i,s_{-i}^*)$ for each $i$ — every player best-responds to everyone else.'],
    int:['No player regrets their choice given what the others did — it\'s a self-enforcing agreement.',
         'It is a fixed point of the joint best-response map: nobody has a profitable unilateral deviation.'],
    ex:['In the Prisoner\'s Dilemma the unique pure Nash equilibrium is mutual defection $(D,D)$, even though $(C,C)$ Pareto-dominates it.',
        'Matching Pennies has no pure equilibrium but a unique mixed one in which each player randomizes $(1/2,1/2)$.'],
    form:['Nash (1950) proved existence in every finite game by applying Kakutani\'s fixed-point theorem to the best-response correspondence on the compact convex set $\\Delta(S)=\\prod_i\\Delta(S_i)$.',
          'Equivalently, equilibria are the zeros of the Nash map where each player minimizes their regret $\\max_{s_i\'}u_i(s_i\',s_{-i})-u_i(s)$.'],
    app:['Central to oligopoly theory, routing games, auction design, and evolutionary biology.',
         'Provides the baseline benchmark for the Price of Anarchy and mechanism design guarantees.']}),

  kb('prisoners_dilemma','Prisoner\'s Dilemma',['pd','prisoners dilemma','prisoner dilemma'],
    'Canonical 2x2 game where individually rational defection leads to a Pareto-inferior outcome.',{
    def:['A symmetric $2\\times 2$ game with payoffs satisfying $T>R>P>S$ and $2R>T+S$, where $C$ and $D$ denote Cooperate and Defect.',
         'A standard payoff matrix is $\\begin{pmatrix}(R,R)&(S,T)\\\\(T,S)&(P,P)\\end{pmatrix}$ with e.g. $(T,R,P,S)=(5,3,1,0)$.'],
    int:['Each player strictly prefers to defect regardless of the opponent, yet mutual cooperation is strictly better than mutual defection.',
         'It exposes the tension between individual incentives and collective welfare — rationality yields $(P,P)$ rather than $(R,R)$.'],
    ex:['With $(T,R,P,S)=(5,3,1,0)$, defecting yields $5$ vs cooperating $3$ if the other cooperates, and $1$ vs $0$ if the other defects, so $D$ strictly dominates $C$.',
        'Real-world analogs: arms races, cartel cheating, doping in sports, and climate-change free-riding.'],
    form:['In the one-shot game $D$ is strictly dominant; the unique Nash equilibrium is $(D,D)$. In infinitely repeated play with discount factor $\\delta\\ge (T-R)/(T-P)$, cooperation can be sustained by trigger strategies (Folk Theorem).',
          'Axelrod\'s tournaments showed that simple reciprocal strategies like Tit-for-Tat often prevail in iterated play.'],
    app:['Models public-goods provision, oligopoly collusion stability, and international treaty enforcement.','It motivates mechanism design, reputation, and long-run relationships.']}),

  kb('dom_strat','Dominant Strategy',['dominance','strictly dominant','weakly dominant'],
    'A strategy that yields at least as high a payoff as any alternative regardless of others\' play.',{
    def:['$s_i$ strictly dominates $s_i\'$ if $u_i(s_i,s_{-i})>u_i(s_i\',s_{-i})$ for all $s_{-i}\\in S_{-i}$; weak dominance replaces $>$ with $\\ge$ (strict for some $s_{-i}$).',
         'A strategy is (strictly) dominant if it (strictly) dominates every other strategy in $S_i$.'],
    int:['It\'s the best choice for player $i$ no matter what the opponents do — there is no scenario in which switching is better.',
         'A dominant strategy makes strategic reasoning unnecessary: you should play it unconditionally.'],
    ex:['In the Prisoner\'s Dilemma, Defect strictly dominates Cooperate.',
        'In a second-price (Vickrey) auction, truthfully bidding your value is a weakly dominant strategy.'],
    form:['If every player has a strictly dominant strategy, the resulting profile is the unique Nash equilibrium (a dominant-strategy equilibrium).',
          'Iterated elimination of strictly dominated strategies never removes a Nash equilibrium and commutes with order.'],
    app:['Dominant-strategy incentive compatibility (DSIC) is the gold standard in mechanism design — see VCG mechanisms.','Used to simplify analysis of auctions, voting rules, and contract design.']}),

  kb('mixed_strat','Mixed Strategy',['mixed','randomized strategy','mixing'],
    'A probability distribution over a player\'s pure strategies.',{
    def:['A mixed strategy for player $i$ is $\\sigma_i\\in\\Delta(S_i)$ with $\\sigma_i(s_i)\\ge 0$ and $\\sum_{s_i}\\sigma_i(s_i)=1$; expected payoff is $u_i(\\sigma)=\\sum_s\\prod_j\\sigma_j(s_j)\\,u_i(s)$.',
         'A mixed Nash equilibrium requires each player to be indifferent among all pure strategies in their support.'],
    int:['Randomization is optimal when predictability is exploitable — it keeps opponents guessing.',
         'A mixing player must be indifferent among the pure strategies in the support, otherwise they\'d collapse to a pure best response.'],
    ex:['In Matching Pennies, each player mixes $(1/2,1/2)$ giving expected payoff $0$.',
        'Rock-Paper-Scissors has a unique symmetric mixed equilibrium $(1/3,1/3,1/3)$ with expected payoff $0$.'],
    form:['Nash\'s existence theorem guarantees a mixed equilibrium in every finite game. Harsanyi (1973) showed mixing is the limit of slightly perturbed pure-strategy play (purification).',
          'Support characterization: if $\\mathrm{supp}(\\sigma_i^*)=T_i$ then $u_i(s_i,\\sigma_{-i}^*)$ is constant on $T_i$ and $\\ge$ its value off $T_i$.'],
    app:['Used in security games, poker bluffing, penalty-kick analysis, and randomized algorithms.','Essential for analyzing games lacking pure equilibria.']}),

  kb('pure_strat','Pure Strategy',['pure'],
    'A deterministic choice of an action from a player\'s strategy set.',{
    def:['A pure strategy for player $i$ is an element $s_i\\in S_i$; equivalently a degenerate mixed strategy $\\sigma_i$ with $\\sigma_i(s_i)=1$.',
         'In extensive-form games, a pure strategy is a complete contingent plan $s_i:H_i\\to A$ assigning an action at every information set $h\\in H_i$.'],
    int:['Pure strategies commit to one action without randomization.','They are the building blocks from which mixed strategies are constructed.'],
    ex:['In Battle of the Sexes, $(Opera,Opera)$ and $(Football,Football)$ are the two pure Nash equilibria.',
        'Matching Pennies has no pure Nash equilibrium.'],
    form:['A finite game may have zero, one, or many pure Nash equilibria; existence is not guaranteed unlike the mixed case.',
          'In supermodular games with monotone best responses, pure equilibria always exist (Topkis-Milgrom-Roberts).'],
    app:['Frequently used in coordination problems, supply-chain contracting, and engineering design.','Often preferred for interpretability when they exist.']}),

  kb('zero_sum','Zero-Sum Game',['zerosum','constant-sum','strictly competitive'],
    'A game in which one player\'s gain exactly offsets the others\' losses.',{
    def:['A two-player game is zero-sum if $u_1(s)+u_2(s)=0$ for all $s\\in S_1\\times S_2$; it is constant-sum if $u_1(s)+u_2(s)=c$.',
         'Equivalently it is described by a single payoff matrix $A\\in\\mathbb{R}^{m\\times n}$ with row player maximizing $x^\\top A y$ and column player minimizing.'],
    int:['Pure conflict — whatever one side gains the other loses.','Optimal play is max-min / min-max: maximize your guaranteed payoff against a worst-case opponent.'],
    ex:['Chess, Go, and Matching Pennies are zero-sum (draws counted as split).',
        'A rock-paper-scissors tournament with $\\{-1,0,+1\\}$ payoffs is zero-sum.'],
    form:['Von Neumann\'s Minimax Theorem: $\\max_x\\min_y x^\\top A y = \\min_y\\max_x x^\\top A y$ in mixed strategies, giving a unique value $v$.',
          'The equilibrium can be computed by linear programming in polynomial time.'],
    app:['Underpins adversarial ML (GANs, robust optimization), pursuit-evasion, and security resource allocation.','LP duality between the two players\' optimization problems is foundational.']}),

  kb('coop_game','Cooperative Game',['coalitional','tu game','characteristic function'],
    'A game where binding agreements among coalitions are allowed; analysis focuses on joint payoffs.',{
    def:['A TU (transferable-utility) game is a pair $(N,v)$ where $N$ is the set of players and $v:2^N\\to\\mathbb{R}$ with $v(\\emptyset)=0$; $v(S)$ is the worth of coalition $S$.',
         'Solutions include the core, the Shapley value, the nucleolus, the bargaining set, and the kernel.'],
    int:['Players can form coalitions and freely redistribute the resulting surplus.',
         'The question shifts from "what will I do" to "how should the joint value be divided".'],
    ex:['Bankruptcy/airport cost-sharing games have rich core and Shapley-value solutions.',
        'A 3-player majority game with $v(S)=1$ iff $|S|\\ge 2$ has empty core but a clear Shapley value $(1/3,1/3,1/3)$.'],
    form:['Key properties: superadditivity $v(S\\cup T)\\ge v(S)+v(T)$ for disjoint $S,T$; convexity $v(S\\cup T)+v(S\\cap T)\\ge v(S)+v(T)$. Convex games always have a nonempty core containing the Shapley value.',
          'Bondareva-Shapley theorem characterizes nonempty core via balanced collections of coalitions.'],
    app:['Cost allocation in utilities, revenue sharing in alliances, voting power, and collaborative ML.','Formalizes fairness notions like symmetry, efficiency, and additivity.']}),

  kb('noncoop_game','Non-Cooperative Game',['non-cooperative'],
    'A game in which binding agreements are not possible; each player chooses independently.',{
    def:['Analysis is via strategic-form or extensive-form games $(N,\\{S_i\\},\\{u_i\\})$ with individual strategy spaces and utilities, solved by equilibrium concepts.',
         'Solutions concepts include Nash, subgame-perfect, Bayesian, and correlated equilibria.'],
    int:['Every agent optimizes privately — cooperation must be self-enforcing.',
         'It is the umbrella framework for most strategic modeling in economics and CS.'],
    ex:['Cournot duopoly, the Prisoner\'s Dilemma, and first-price auctions are non-cooperative.',
        'Traffic routing is naturally non-cooperative — drivers minimize their own travel time.'],
    form:['Nash (1951) proved existence of mixed equilibria in finite non-cooperative games. Refinements tighten predictions in dynamic and incomplete-information settings.',
          'Non-cooperative foundations for cooperative concepts are provided by the Nash program.'],
    app:['Default framework for IO, auction theory, algorithmic game theory, and multi-agent RL.','Self-enforcing cooperation is recovered via repetition or contracts.']}),

  kb('minimax','Minimax Theorem',['von neumann theorem','max-min','minmax'],
    'In any finite two-player zero-sum game, max-min and min-max values coincide in mixed strategies.',{
    def:['Von Neumann (1928): $\\max_{x\\in\\Delta^m}\\min_{y\\in\\Delta^n} x^\\top A y=\\min_{y\\in\\Delta^n}\\max_{x\\in\\Delta^m} x^\\top A y=v(A).$',
         'The common value $v$ is the value of the game; any saddle-point $(x^*,y^*)$ attains it.'],
    int:['Rational worst-case planning yields the same outcome for both sides.',
         'It guarantees an optimal defensive strategy for each player in pure conflict.'],
    ex:['Matching Pennies has value $0$ with optimal mixes $(1/2,1/2)$ for both.',
        'A $3\\times 3$ RPS matrix has value $0$ with $(1/3,1/3,1/3)$ optimal.'],
    form:['Proof by LP duality: the row-player\'s LP $\\max v\\text{ s.t. }A^\\top x\\ge v\\mathbf{1},\\mathbf{1}^\\top x=1$ is dual to the column-player\'s, so strong duality gives the minimax equality.',
          'Generalizations include Sion\'s minimax theorem for quasi-concave/convex payoffs on compact convex sets.'],
    app:['Foundation of LP duality, robust optimization, statistical decision theory, and adversarial training of generative models.','Fictitious play converges to the minimax value in zero-sum games.']}),

  kb('extensive_form','Extensive-Form Game',['game tree','sequential','extensive form'],
    'A representation of sequential play using a rooted tree with information sets.',{
    def:['A tuple $\\langle N,T,\\prec,\\iota,\\mathcal H,\\{u_i\\}\\rangle$: tree $T$ with precedence $\\prec$, player function $\\iota$, information partition $\\mathcal H$ and payoffs on terminal nodes.',
         'A pure strategy specifies an action at every information set; behavior strategies assign distributions over actions per info set.'],
    int:['Models who moves when and what each player knows at the time of their move.',
         'Strategic and extensive forms are equivalent for strategic-form analysis but extensive form captures timing and information.'],
    ex:['The Centipede Game, Stackelberg leader-follower, and sequential bargaining are extensive form.',
        'Any chess position is a node in the extensive-form game of chess.'],
    form:['Kuhn\'s theorem: in games of perfect recall, mixed and behavior strategies are outcome-equivalent.',
          'Zermelo (1913) showed finite perfect-information games have a pure-strategy backward-induction solution.'],
    app:['Used to analyze negotiations, repeated interactions, and multi-stage mechanism design.','Backward induction and subgame perfection are natural here.']}),

  kb('normal_form','Normal-Form Game',['strategic form','matrix game'],
    'A simultaneous-move representation via strategy sets and payoff functions.',{
    def:['A tuple $\\langle N,\\{S_i\\}_{i\\in N},\\{u_i:\\prod_j S_j\\to\\mathbb{R}\\}\\rangle$; two-player finite games are often displayed as a payoff matrix.',
         'Every extensive-form game induces a normal form over strategies (complete contingent plans).'],
    int:['All players choose once and simultaneously, without knowing others\' choices.',
         'It abstracts away timing and information flow to focus on strategy-level reasoning.'],
    ex:['The $2\\times 2$ Prisoner\'s Dilemma matrix is the canonical normal form.',
        'Any $n$-player finite game can be listed as an $n$-dimensional payoff tensor.'],
    form:['Nash equilibria in the normal form always exist in mixed strategies (Nash, 1950).',
          'The normal form captures strategic equivalence classes coarser than extensive-form equivalence.'],
    app:['The default representation for matrix/bimatrix algorithms and LP-based equilibrium computation.','Ubiquitous in AI, IO, and introductory game theory.']}),

  kb('bayesian_game','Bayesian Game',['games of incomplete information','bayes nash','type space'],
    'A game in which players have private information (types) drawn from a common prior.',{
    def:['A Bayesian game is $\\langle N,\\{\\Theta_i\\},p,\\{A_i\\},\\{u_i(a,\\theta)\\}\\rangle$ with type space $\\Theta=\\prod\\Theta_i$ and prior $p\\in\\Delta(\\Theta)$.',
         'A strategy is $\\sigma_i:\\Theta_i\\to\\Delta(A_i)$; a Bayes-Nash equilibrium satisfies $\\sigma_i^*(\\theta_i)\\in\\arg\\max_{a_i}\\mathbb{E}_{\\theta_{-i}|\\theta_i}u_i(a_i,\\sigma_{-i}^*(\\theta_{-i}),\\theta).$'],
    int:['Each player best-responds in expectation over the others\' possible private information.',
         'Private information is modeled as a "type" that parametrizes payoffs or beliefs.'],
    ex:['In a first-price auction with i.i.d. private values $v_i\\sim U[0,1]$, the symmetric BNE bid is $b(v)=\\frac{n-1}{n}v$.',
        'Signaling models of labor markets (Spence) and insurance (Rothschild-Stiglitz) are Bayesian.'],
    form:['Harsanyi (1967-68) showed any game of incomplete information has a Bayesian equivalent via the type-space transformation.',
          'Common-prior assumption links beliefs consistently through Bayesian updating.'],
    app:['Foundation of auction theory, contract theory, and information economics.','Pervasive in online advertising and recommender systems.']}),

  kb('repeated_game','Repeated Game',['iterated game','supergame'],
    'A stage game played repeatedly, allowing histories to influence future play.',{
    def:['Given stage game $G$, the $T$-stage repeated game has payoff $\\sum_{t=1}^T \\delta^{t-1}u_i(a^t)$ with discount factor $\\delta\\in[0,1]$; $T=\\infty$ gives the infinitely repeated game.',
         'Strategies are history-dependent maps $\\sigma_i:\\bigcup_t H_t\\to\\Delta(A_i)$.'],
    int:['Players can condition today\'s play on past behavior, supporting reputations and threats.',
         'Repetition transforms static dilemmas into opportunities for cooperation via credible punishments.'],
    ex:['Tit-for-Tat sustains cooperation in the infinitely repeated Prisoner\'s Dilemma for $\\delta$ large enough.',
        'Grim-trigger supports any individually rational feasible payoff in repeated oligopoly.'],
    form:['Folk Theorem: any individually rational feasible payoff can be sustained as a subgame-perfect equilibrium of the infinitely repeated game for $\\delta$ close enough to $1$.',
          'Finitely repeated games with unique stage-game equilibria collapse by backward induction to stage-game play.'],
    app:['Models long-run business relationships, cartel stability, and reputation in platforms.','Connects to reinforcement-learning convergence in multi-agent systems.']}),

  kb('evo_gt','Evolutionary Game Theory',['egt','evolution'],
    'Studies strategy frequencies in large populations under selection and mutation.',{
    def:['Strategies are heritable phenotypes; fitness equals expected game payoff against a random opponent from the current population state $x\\in\\Delta(S)$.',
         'Solution concepts include evolutionarily stable strategies (ESS) and asymptotically stable rest points of evolutionary dynamics.'],
    int:['No foresight or rationality is required — selection substitutes for best-response reasoning.',
         'Equilibrium emerges from differential reproduction of successful strategies.'],
    ex:['The Hawk-Dove game admits a mixed ESS at $x_H=v/c$ for value $v$ and cost $c$.',
        'Sex-ratio evolution gives a $1:1$ ratio as an ESS (Fisher).'],
    form:['Every ESS is a Nash equilibrium of the symmetric game; the converse requires additional stability conditions.',
          'Replicator dynamics link EGT to Lyapunov analysis and relative entropy.'],
    app:['Biology (animal conflicts, signaling), cultural evolution, learning in games, and multi-agent RL.','Explains seemingly irrational persistence of cooperation in animal populations.']}),

  kb('ess','Evolutionarily Stable Strategy',['ess','evolutionary stable'],
    'A strategy that, if adopted by the population, cannot be invaded by any rare mutant.',{
    def:['$x^*$ is an ESS if for every $y\\ne x^*$ there exists $\\bar\\varepsilon>0$ such that $u(x^*,\\,\\varepsilon y+(1-\\varepsilon)x^*)>u(y,\\,\\varepsilon y+(1-\\varepsilon)x^*)$ for all $\\varepsilon\\in(0,\\bar\\varepsilon)$.',
         'Maynard Smith-Price equivalent: $u(x^*,x^*)\\ge u(y,x^*)$ for all $y$, and if $u(x^*,x^*)=u(y,x^*)$ then $u(x^*,y)>u(y,y)$.'],
    int:['Once nearly everyone plays $x^*$, no small group of mutants can earn strictly more and thus they cannot spread.',
         'ESS is a local stability refinement of symmetric Nash.'],
    ex:['Hawk-Dove: the mixed ESS is $x_H^*=v/c$ when $c>v$.',
        'In Rock-Paper-Scissors, the unique symmetric Nash $(1/3,1/3,1/3)$ is not an ESS — populations cycle under replicator dynamics.'],
    form:['Every ESS is a Nash equilibrium; not every Nash equilibrium is an ESS. An ESS is asymptotically stable under replicator dynamics (Taylor-Jonker).',
          'For matrix games, ESS $\\Leftrightarrow$ $x^*$ is a local strict maximum of $u(x,x)$ on an invariant face.'],
    app:['Explains animal contests, plant seed strategies, honest signaling, and robust equilibrium selection.','Widely used to motivate equilibrium refinements in economics.']}),

  kb('replicator','Replicator Dynamics',['replicator equation'],
    'ODEs describing how strategy frequencies evolve under selection proportional to fitness.',{
    def:['$\\dot x_i = x_i\\bigl(f_i(x)-\\bar f(x)\\bigr)$, where $f_i(x)=(Ax)_i$ is the fitness of pure strategy $i$ and $\\bar f(x)=x^\\top A x$ is the average.',
         'The simplex $\\Delta(S)$ and its faces are invariant under the flow.'],
    int:['Strategies doing better than average grow; those doing worse decline.',
         'No rationality is assumed — the dynamics are a pure selection model.'],
    ex:['Rock-Paper-Scissors under replicator dynamics exhibits closed orbits around the center $(1/3,1/3,1/3)$.',
        'In the Hawk-Dove game trajectories converge to the mixed ESS $x_H=v/c$.'],
    form:['For symmetric games, every ESS is asymptotically stable; strict Nash equilibria are asymptotically stable; interior Nash equilibria are Lyapunov-stable. Relative entropy to a Nash equilibrium is a Lyapunov function for doubly symmetric games.',
          'Related to Lotka-Volterra equations via a nonlinear change of variables.'],
    app:['Used in population genetics, cultural learning, congestion adaptation, and multi-agent RL convergence analysis.','Models of social learning via imitation yield the same ODE.']}),

  kb('stackelberg','Stackelberg Competition',['stackelberg','leader-follower'],
    'A sequential duopoly in which a leader commits to an output and the follower best-responds.',{
    def:['Leader chooses $q_1$ to maximize $\\pi_1(q_1,q_2^*(q_1))$ where $q_2^*(q_1)\\in\\arg\\max_{q_2}\\pi_2(q_1,q_2)$ is the follower\'s best response.',
         'The solution concept is subgame perfect equilibrium, obtained by backward induction.'],
    int:['Committing first can be valuable — the leader exploits the follower\'s rational response.',
         'First-mover advantage arises when best responses slope downward.'],
    ex:['With linear demand $P=a-Q$ and zero cost, Stackelberg yields $q_1=a/2$, $q_2=a/4$, giving profits $a^2/8$ and $a^2/16$ — the leader earns more than Cournot\'s $a^2/9$.',
        'Security games deploy randomized commitments against best-responding attackers (Stackelberg security).'],
    form:['Leader\'s program is a bilevel optimization $\\max_{q_1}\\pi_1(q_1, q_2^*(q_1))$ — generally nonconvex but tractable in standard demand systems.',
          'Without commitment power, the game collapses to simultaneous Cournot.'],
    app:['Industrial organization, pricing, and entry deterrence.','Stackelberg security games deploy patrol schedules at airports (ARMOR, IRIS).']}),

  kb('cournot','Cournot Competition',['cournot','quantity competition'],
    'A simultaneous-move duopoly/oligopoly with quantity as the strategic variable.',{
    def:['Firms simultaneously choose quantities $q_i\\ge 0$ and receive profit $\\pi_i=q_i P(Q)-c_i(q_i)$ where $Q=\\sum_j q_j$.',
         'The Cournot-Nash equilibrium solves $\\partial\\pi_i/\\partial q_i=0$ for all $i$ simultaneously.'],
    int:['Each firm takes rivals\' output as given and equates marginal revenue to marginal cost.',
         'Equilibrium lies between monopoly and perfect competition.'],
    ex:['With linear demand $P=a-Q$ and zero cost, symmetric equilibrium is $q_i^*=a/(n+1)$ and price $P=a/(n+1)$; as $n\\to\\infty$, $P\\to 0$.',
        'Two firms with these parameters earn $\\pi=a^2/9$ each.'],
    form:['Best response $q_i^*(q_{-i})=\\tfrac{1}{2}(a-\\sum_{j\\ne i}q_j)$ in the linear case; intersection gives the Nash equilibrium.',
          'As $n\\to\\infty$, the Cournot equilibrium converges to the competitive outcome (Walras).'],
    app:['Benchmark model for quantity-setting oligopolies and merger analysis.','Used to bound deadweight loss from imperfect competition.']}),

  kb('bertrand','Bertrand Competition',['bertrand','price competition'],
    'Simultaneous price-setting competition among firms producing a homogeneous good.',{
    def:['Firms simultaneously post prices $p_i$; demand goes entirely to the lowest price (split if tied). Profit is $\\pi_i=(p_i-c)D(p_i)\\cdot \\mathbf 1\\{p_i\\le p_{-i}\\}\\cdot\\text{share}.',
         'The "Bertrand paradox" arises with identical goods and marginal cost $c$: the unique Nash equilibrium is $p_i=c$ for all $i$.'],
    int:['Price undercutting drives price to marginal cost with even as few as two firms.',
         'Tiny asymmetries in cost or differentiation change the picture dramatically.'],
    ex:['Two symmetric firms with constant marginal cost $c$ both price at $c$ in equilibrium, earning zero profit.',
        'Differentiated Bertrand with logit demand yields positive equilibrium markups.'],
    form:['With capacity constraints (Edgeworth-Bertrand) or product differentiation, equilibrium prices exceed marginal cost.',
          'Kreps-Scheinkman: Cournot outcomes emerge as the subgame perfect equilibrium of a two-stage capacity-then-price game.'],
    app:['Explains why concentrated markets still exhibit competitive pricing if products are homogeneous.','Motivates product differentiation as a profit-protection strategy.']}),

  kb('auction_theory','Auction Theory',['auctions'],
    'Study of resource allocation via bidding mechanisms.',{
    def:['Standard auction formats include first-price sealed-bid, second-price (Vickrey), English (ascending), and Dutch (descending).',
         'With private values $v_i$ i.i.d.\\ from $F$, a symmetric equilibrium bid in the first-price auction is $b(v)=\\mathbb E[\\max_{j\\ne i}v_j\\mid v_i=v]$.'],
    int:['Different formats trade off revenue, efficiency, and strategic complexity.',
         'Under symmetric risk-neutral private values all four standard auctions yield the same expected revenue — the Revenue Equivalence Theorem.'],
    ex:['In a Vickrey auction, bidding $b_i=v_i$ is weakly dominant and the highest value wins paying the second-highest bid.',
        'In eBay-style ascending auctions, proxy bidding implements the Vickrey outcome under IPV.'],
    form:['Revenue Equivalence (Myerson-Riley-Samuelson): any symmetric IPV auction allocating to the highest-valuation bidder with the losers paying zero has the same expected revenue.',
          'Myerson\'s optimal auction uses virtual valuations $\\psi(v)=v-\\frac{1-F(v)}{f(v)}$ and allocates to the bidder with highest $\\psi$ if $\\ge 0$.'],
    app:['Used in spectrum auctions, online ad exchanges (GSP, VCG), treasury bonds, and art sales.','Basis for algorithmic mechanism design.']}),

  kb('vickrey','Vickrey Auction',['second price','second-price sealed bid'],
    'A sealed-bid auction where the highest bidder wins and pays the second-highest bid.',{
    def:['Winner: $i^*=\\arg\\max_j b_j$; payment: $p_{i^*}=\\max_{j\\ne i^*} b_j$; all others pay $0$.',
         'With single-unit private values, truthful bidding $b_i=v_i$ is weakly dominant.'],
    int:['Because price is set by others, your bid only affects whether you win, not how much you pay — so truth-telling is optimal.',
         'Incentive compatibility means bidders do not need to strategize over others\' valuations.'],
    ex:['Values $(10,7,4)$: bidder 1 wins and pays $7$, netting surplus $3$.',
        'Under symmetric IPV, expected revenue equals that of the first-price auction (Revenue Equivalence).'],
    form:['The Vickrey auction is a special case of the VCG mechanism for a single indivisible good.',
          'Generalizes to combinatorial settings as VCG, charging each winner their marginal externality on others.'],
    app:['Historical use in stamp auctions; conceptual basis for GSP in sponsored-search ads and many computerized markets.','Cornerstone example in mechanism-design teaching.']}),

  kb('mech_design','Mechanism Design',['reverse game theory','social choice mechanism'],
    'Designing the rules of a game so that equilibrium behavior yields desired outcomes.',{
    def:['A mechanism is $(M,g)$ with message space $M=\\prod M_i$ and outcome function $g:M\\to X$. It implements social choice function $f$ in equilibrium concept $\\sigma$ if $g(\\sigma^*(\\theta))=f(\\theta)$ for all type profiles $\\theta$.',
         'Goals typically include efficiency, budget balance, individual rationality, and incentive compatibility.'],
    int:['Design the rules backwards from the outcome you want.',
         'Anticipate strategic play and shape incentives so truthfulness or efficiency emerges.'],
    ex:['The VCG mechanism implements efficient allocation in dominant strategies.',
        'Optimal auctions (Myerson) maximize expected revenue subject to Bayesian incentive compatibility.'],
    form:['Revelation Principle: any outcome implementable by some mechanism is implementable by a direct, incentive-compatible mechanism $f:\\Theta\\to X$.',
          'Myerson-Satterthwaite impossibility: no mechanism for bilateral trade is simultaneously efficient, individually rational, budget-balanced, and Bayesian incentive-compatible.'],
    app:['Spectrum auctions, matching markets (kidney exchange, school choice), online ad auctions, and procurement.','Central in algorithmic mechanism design and EC theory.']}),

  kb('revelation','Revelation Principle',['revelation'],
    'Any equilibrium outcome of any mechanism can be reproduced by a direct truthful mechanism.',{
    def:['If mechanism $(M,g)$ implements $f$ in (Bayes-)Nash equilibrium $\\sigma^*$, then the direct mechanism $f=g\\circ\\sigma^*$ is (Bayesian) incentive-compatible and implements $f$ truthfully.',
         'Variants exist for dominant-strategy and Nash implementation.'],
    int:['Rather than searching over all possible message spaces, designers can restrict attention to direct truthful mechanisms without loss of generality.',
         'It reduces mechanism design to choosing a social-choice rule subject to IC constraints.'],
    ex:['The Vickrey auction is the direct truthful version of the English ascending auction.',
        'Any iterative bidding process implementing the same allocation has a direct-truthful counterpart.'],
    form:['Formally a "without loss of generality" theorem that massively reduces the design space.',
          'Caveats: does not address computational tractability, multiplicity of equilibria, or full implementation.'],
    app:['Foundational for auction, voting, and contract design analysis.','Allows a clean separation between incentive compatibility and the social objective.']}),

  kb('shapley','Shapley Value',['shapley','fair allocation'],
    'A unique fair allocation in cooperative games satisfying efficiency, symmetry, dummy, and additivity.',{
    def:['$\\phi_i(v)=\\sum_{S\\subseteq N\\setminus\\{i\\}}\\dfrac{|S|!\\,(|N|-|S|-1)!}{|N|!}\\bigl(v(S\\cup\\{i\\})-v(S)\\bigr).$',
         'Equivalently an average of player $i$\'s marginal contribution over all orderings of $N$.'],
    int:['Each player is paid their expected marginal contribution if players join in a uniformly random order.',
         'It is the unique payoff vector satisfying four natural fairness axioms.'],
    ex:['For the majority game $v(S)=\\mathbf 1\\{|S|\\ge 2\\}$ with $N=\\{1,2,3\\}$, $\\phi=(1/3,1/3,1/3)$.',
        'Airport cost-sharing: incremental runway costs yield Shapley values that equal the average cost-per-user.'],
    form:['Shapley (1953) characterized $\\phi$ uniquely via efficiency ($\\sum\\phi_i=v(N)$), symmetry, dummy/null player, and linearity/additivity.',
          'For convex games, the Shapley value lies in the core (Shapley, 1971).'],
    app:['Cost allocation, feature attribution in ML (SHAP values), power indices in voting, and collaborative learning.','Interpretable ML tool (SHAP) that has become standard practice.']}),

  kb('core','Core (of a Cooperative Game)',['core'],
    'The set of coalition-stable payoff allocations.',{
    def:['$\\text{Core}(v)=\\{x\\in\\mathbb{R}^N:\\sum_{i\\in N}x_i=v(N),\\;\\sum_{i\\in S}x_i\\ge v(S)\\;\\forall S\\subseteq N\\}.$',
         'No coalition can strictly improve by breaking off — every coalition earns at least what it can guarantee.'],
    int:['Allocations in the core are immune to any coalitional deviation.',
         'Think of it as a set-valued solution generalizing individual rationality to every subgroup.'],
    ex:['In the majority game with three players, the core is empty.',
        'In a market with one seller and many buyers, the core converges to the competitive equilibrium as the market grows (Debreu-Scarf).'],
    form:['Bondareva-Shapley Theorem: the core is nonempty iff the game is balanced — any balanced collection of weights satisfies $\\sum_S\\lambda_S v(S)\\le v(N)$.',
          'Convex games have nonempty cores with the Shapley value as the barycenter.'],
    app:['Market equilibria, assignment games, and fair resource allocation.','Provides a "no-blocking" stability concept across all coalitions.']}),

  kb('coalition','Coalition Formation',['coalitions','partition function'],
    'Study of which coalitions form and how they share surplus.',{
    def:['Partition function games $v:\\mathcal P(N)\\to\\mathbb{R}$ assign value to each coalition within a coalition structure (partition).',
         'Hedonic games assign each player a preference over coalitions containing them and study stable partitions.'],
    int:['Beyond "everyone cooperates", who teams up with whom and why?',
         'Stability, fairness, and efficiency of partitions are all considered.'],
    ex:['In hedonic matching (roommate problem), no-blocking partitions may not exist.',
        'In political coalitions, the Banzhaf and Shapley-Shubik power indices measure pivotal influence.'],
    form:['Core-stability, Nash-stability, and individual stability each capture different robustness concepts for partitions.',
          'Even in simple hedonic games, computing stable partitions can be NP-hard.'],
    app:['Political alliances, R&D consortia, group formation in social networks, and team formation in distributed computing.','Connects to matching theory and hedonic preferences.']}),

  kb('nash_bargaining','Nash Bargaining Solution',['nash bargaining','bargaining solution'],
    'The unique allocation satisfying Pareto-efficiency, symmetry, scale invariance, and IIA.',{
    def:['Given feasible set $F\\subseteq\\mathbb{R}^2$ and disagreement point $d$, $\\phi(F,d)=\\arg\\max_{x\\in F,\\,x\\ge d}(x_1-d_1)(x_2-d_2).$',
         'Generalizes to $n$ players via the weighted Nash product $\\prod_i(x_i-d_i)^{\\alpha_i}$.'],
    int:['Maximize the product of gains from agreement relative to the outside option.',
         'It is the unique "fair" solution under Nash\'s four axioms.'],
    ex:['Splitting \\$1 with $d=(0,0)$: the Nash solution is $(0.5,0.5)$; if $d=(0.3,0)$, it becomes $(0.65,0.35)$.',
        'Wage bargaining with threat points gives each side a share of the surplus proportional to bargaining strength.'],
    form:['Nash (1950) axiomatization: Pareto-efficiency + symmetry + invariance to affine utility transformations + IIA uniquely identifies the product-maximizer.',
          'Rubinstein (1982) provided a non-cooperative microfoundation via alternating-offers bargaining.'],
    app:['Labor-management negotiations, trade agreements, and divorce settlements.','Workhorse in matching/search models of the labor market.']}),

  kb('rubinstein','Rubinstein Bargaining',['alternating offers','rubinstein-stahl'],
    'A non-cooperative alternating-offers model of bargaining with a unique subgame-perfect outcome.',{
    def:['Two players alternate offers to split a pie of size $1$; discount factors $\\delta_1,\\delta_2\\in(0,1)$ reflect impatience.',
         'The unique SPE has player 1 offering $x_1^*=(1-\\delta_2)/(1-\\delta_1\\delta_2)$ and it being accepted immediately.'],
    int:['Impatient players concede faster; first-mover advantage vanishes as frictions disappear.',
         'The ability to delay is an implicit threat that drives the equilibrium split.'],
    ex:['With $\\delta_1=\\delta_2=\\delta$, the proposer gets $1/(1+\\delta)$ and the responder $\\delta/(1+\\delta)$.',
        'As $\\delta\\to 1$, the outcome converges to the symmetric Nash bargaining solution $(1/2,1/2)$.'],
    form:['Proved by stationary backward-induction: equate each player\'s offer to what they could obtain by waiting one period and proposing themselves.',
          'Provides the "Nash program" microfoundation for the Nash bargaining solution.'],
    app:['Microfoundations for search-matching, wage determination, and bilateral trade.','Extensions incorporate outside options, risk of breakdown, and incomplete information.']}),

  kb('corr_eq','Correlated Equilibrium',['correlated equilibrium','aumann correlated'],
    'An equilibrium in which players obey recommendations from a common randomization device.',{
    def:['A distribution $\\mu\\in\\Delta(S)$ is a correlated equilibrium if $\\sum_{s_{-i}}\\mu(s_i,s_{-i})\\bigl(u_i(s_i,s_{-i})-u_i(s_i\',s_{-i})\\bigr)\\ge 0$ for all $i,s_i,s_i\'$.',
         'Given the recommendation $s_i$, following it weakly dominates any deviation $s_i\'$ in expectation over $s_{-i}\\mid s_i$.'],
    int:['A trusted signal coordinates play — think of a traffic light rotating priorities.',
         'Every Nash equilibrium is correlated, but correlated equilibria can achieve strictly higher welfare.'],
    ex:['In Chicken with payoffs $(0,0),(4,1),(1,4),(-5,-5)$, correlated play with $(D,S),(S,D),(S,S)$ each with probability $1/3$ gives expected payoff $10/3$ — higher than any Nash.',
        'Traffic lights implement a correlated equilibrium between arriving drivers.'],
    form:['Aumann (1974): the set of correlated equilibria is convex, contains all Nash equilibria, and can be computed via linear programming.',
          'No-regret dynamics converge to the set of correlated equilibria in every finite game (Hart-Mas-Colell).'],
    app:['Explains social norms and conventions as coordination devices.','Computationally attractive and learnable via simple algorithms.']}),

  kb('spe','Subgame Perfect Equilibrium',['spe','subgame perfection'],
    'A Nash equilibrium that also prescribes a Nash equilibrium in every subgame.',{
    def:['A strategy profile $\\sigma^*$ is a subgame perfect equilibrium if its restriction to every subgame is a Nash equilibrium of that subgame.',
         'Found via backward induction in finite games of perfect information.'],
    int:['Rules out non-credible threats by requiring rational play even off the equilibrium path.',
         'A refinement of Nash that respects sequential rationality.'],
    ex:['In Stackelberg competition, the SPE is the leader-follower outcome obtained by backward induction.',
        'In the entry-deterrence game, threats to fight that would be irrational ex post are not subgame perfect.'],
    form:['Selten (1965) introduced SPE; for finite perfect-information games it coincides with the backward-induction path.',
          'Zermelo\'s theorem guarantees existence in finite perfect-information games.'],
    app:['Sequential bargaining, dynamic oligopoly, and repeated-game analysis.','Essential when credibility of continuation play matters.']}),

  kb('pbe','Perfect Bayesian Equilibrium',['pbe','perfect bayesian'],
    'A refinement for dynamic games of incomplete information pairing strategies with beliefs.',{
    def:['A PBE is $(\\sigma,\\mu)$ such that (i) each $\\sigma_i$ is sequentially rational given beliefs $\\mu$ and (ii) $\\mu$ is updated via Bayes\' rule on the equilibrium path (and reasonably off-path).',
         'Stronger refinements include sequential equilibrium (Kreps-Wilson) which requires beliefs to be the limit of fully mixed strategies.'],
    int:['Beliefs are an integral part of the solution — players best-respond given what they believe about private information at each decision point.',
         'It is the natural refinement for signaling and reputation games.'],
    ex:['In Spence\'s signaling model, a PBE involves high-ability workers choosing education levels that low-ability workers would not imitate.',
        'Separating and pooling equilibria in signaling games are classified by PBE.'],
    form:['Sequential equilibrium strengthens PBE by requiring consistent beliefs via a trembling approximation.',
          'Intuitive criterion (Cho-Kreps) further refines signaling equilibria via off-path belief restrictions.'],
    app:['Job-market signaling, reputation models, bargaining under incomplete information, and cheap talk.','Used to analyze dynamic corporate finance and political-economy models.']}),

  kb('trembling','Trembling-Hand Perfection',['trembling hand','selten perfect'],
    'An equilibrium robust to small probabilities of mistakes.',{
    def:['$\\sigma^*$ is trembling-hand perfect if it is the limit of a sequence of totally mixed $\\varepsilon$-equilibria as $\\varepsilon\\to 0$.',
         'Equivalently, best-responding against small trembles ($\\sigma_{-i}^\\varepsilon$) still prescribes the original strategy.'],
    int:['Players may occasionally make mistakes, and equilibrium should remain optimal under this perturbation.',
         'It rules out weakly dominated strategies that are fragile to tiny errors.'],
    ex:['Selten (1975) motivated the concept using a simple game where weakly dominated strategies survive Nash but not trembling-hand perfection.',
        'In 2-player normal form games, trembling-hand perfection coincides with playing undominated best responses.'],
    form:['Every trembling-hand perfect equilibrium is a Nash equilibrium that uses no weakly dominated strategies.',
          'In the extensive form, the analog is subgame-perfect trembling-hand perfection, strengthened further by sequential equilibrium.'],
    app:['Motivates robust mechanism design and evolutionary robustness.','Commonly invoked to discard weakly dominated equilibria.']}),

  kb('battle_of_sexes','Battle of the Sexes',['bos','battle of sexes'],
    'A coordination game with asymmetric preferences over the two coordinated outcomes.',{
    def:['Payoff matrix $\\begin{pmatrix}(2,1)&(0,0)\\\\(0,0)&(1,2)\\end{pmatrix}$ representing two activities each player prefers differently but both prefer coordinating.',
         'Two pure Nash equilibria and one mixed Nash equilibrium.'],
    int:['Both want to be together; they disagree on where.',
         'Highlights equilibrium selection challenges in coordination games.'],
    ex:['Pure equilibria: $(O,O)$ and $(F,F)$ where one player prefers one and the other prefers the other.',
        'Mixed equilibrium has player 1 choose $O$ with probability $2/3$ and player 2 choose $O$ with probability $1/3$.'],
    form:['Payoff-dominance selects $(O,O)$ for player 1 and $(F,F)$ for player 2 — they disagree. Risk-dominance and communication can break the tie.',
          'Correlated equilibrium expands the set of welfare-improving outcomes.'],
    app:['Standards battles (VHS vs Betamax), meeting coordination, and platform choice.','Workhorse example in equilibrium selection and cheap-talk analysis.']}),

  kb('hawk_dove','Hawk-Dove Game',['hawk dove','chicken in biology'],
    'A symmetric 2x2 conflict game used to model animal contests.',{
    def:['Payoffs: $u(H,H)=(v-c)/2$, $u(H,D)=v$, $u(D,H)=0$, $u(D,D)=v/2$ for resource value $v$ and fight cost $c$.',
         'When $c>v$, the ESS is mixed with $x_H^*=v/c$.'],
    int:['Hawks always escalate; Doves always retreat. Neither pure strategy is evolutionarily stable when escalation is costly.',
         'Populations settle at a mix where the expected payoff to Hawks and Doves equalizes.'],
    ex:['With $v=2,c=4$: $x_H^*=1/2$, giving expected payoff $1/2$ for both types.',
        'Observed frequencies of aggressive vs. submissive individuals in many species approximate mixed ESS.'],
    form:['Equivalent to Chicken in economics when costs exceed rewards.',
          'Under replicator dynamics, trajectories converge to the mixed ESS from any interior start.'],
    app:['Animal-conflict theory, business "chicken" dynamics, and territorial disputes.','Foundational example in evolutionary stability analysis.']}),

  kb('stag_hunt','Stag Hunt',['stag-hunt','assurance game'],
    'A coordination game where mutual cooperation on the risky action maximizes welfare.',{
    def:['Payoffs $\\begin{pmatrix}(a,a)&(b,c)\\\\(c,b)&(d,d)\\end{pmatrix}$ with $a>c\\ge d>b$; pure equilibria are $(S,S)$ and $(H,H)$.',
         'With $(a,b,c,d)=(5,0,4,3)$, stag hunting yields $5$ if both cooperate; hare hunting gives $3$ safely.'],
    int:['Everyone gains more by hunting the stag together, but hunting hare alone is safer.',
         'Tension between payoff-dominance (stag) and risk-dominance (hare).'],
    ex:['A team project where collective effort yields $5$ each, individual effort $3$, and being the lone cooperator $0$.',
        'International environmental agreements where only joint effort protects a common resource.'],
    form:['Harsanyi-Selten: $(S,S)$ is payoff-dominant, $(H,H)$ is risk-dominant. Experimentally, risk-dominance often prevails.',
          'Infinitely repeated play can select $(S,S)$ under sufficient patience.'],
    app:['Models trust and assurance in coalitions, currency unions, and network standards.','Rousseau\'s original parable of cooperation.']}),

  kb('chicken','Chicken Game',['chicken','hawk-dove economic'],
    'An anti-coordination game where both players prefer to yield if the other stays the course.',{
    def:['Payoffs $\\begin{pmatrix}(0,0)&(-1,1)\\\\(1,-1)&(-10,-10)\\end{pmatrix}$: mutual swerve $(0,0)$, one yields $(\\pm 1)$, mutual crash $(-10,-10)$.',
         'Two pure Nash equilibria (one yields, the other does not) and one mixed.'],
    int:['Commitment or bluster can force the rival to yield.',
         'Miscoordination is catastrophic — both "holding" leads to disaster.'],
    ex:['Cuban Missile Crisis is a textbook application: two nuclear powers on a collision course.',
        'Legislative budget standoffs exhibit chicken-style brinkmanship.'],
    form:['Schelling (1960): visible commitment — such as throwing away your steering wheel — is a rational move that shifts the equilibrium in your favor.',
          'Correlated equilibrium strictly improves average welfare over all Nash equilibria.'],
    app:['Crisis bargaining, union-management strikes, and military deterrence.','Classic teaching example for commitment devices.']}),

  kb('matching_pennies','Matching Pennies',['matching pennies','odd-even'],
    'A zero-sum $2\\times 2$ game with no pure equilibrium and a unique uniform mixed equilibrium.',{
    def:['Payoff matrix $\\begin{pmatrix}(1,-1)&(-1,1)\\\\(-1,1)&(1,-1)\\end{pmatrix}$ where player 1 wins if the pennies match.',
         'Unique Nash equilibrium: both mix $(1/2,1/2)$ with value $0$.'],
    int:['One player wins when the pennies match; the other when they mismatch.',
         'Any deterministic strategy is exploitable — so both must randomize.'],
    ex:['Soccer penalty kicks between kicker and goalie approximate a matching-pennies structure; empirical studies find near-equilibrium randomization (Chiappori, Levitt, Groseclose).',
        'Any $2\\times 2$ game with cyclic best responses is strategically equivalent.'],
    form:['Canonical example of a game with no pure Nash equilibrium; demonstrates the necessity of mixed strategies.',
          'Optimal randomization is derived via the minimax theorem.'],
    app:['Penalty kicks, serve direction in tennis, randomized audits, and cybersecurity patrolling.','Base case for teaching mixed-strategy equilibrium.']}),

  kb('ultimatum','Ultimatum Game',['ultimatum'],
    'A two-stage bargaining game highlighting the gap between rational prediction and observed fairness.',{
    def:['Proposer offers a split $(x,1-x)$ of a pie; responder accepts (payoffs $(x,1-x)$) or rejects (payoffs $(0,0)$).',
         'Subgame-perfect equilibrium: proposer offers $x\\to 1$, responder accepts any $x<1$.'],
    int:['Self-interested rationality predicts a near-zero offer accepted; experiments show offers of $40$-$50$% and rejection of small offers.',
         'Fairness, reciprocity, and spite enter the empirical picture.'],
    ex:['In the classical Güth-Schmittberger-Schwarze (1982) experiment, modal offers are $50/50$ and offers below $20$% are routinely rejected.',
        'Dictator-game variants remove responder power to isolate pure altruism.'],
    form:['SPE predictions fail empirically — led to behavioral economics models such as inequity aversion (Fehr-Schmidt) and reciprocity (Rabin).',
          'Evolutionary models with reputational tracking recover near-fair offers.'],
    app:['Behavioral economics, experimental game theory, and cross-cultural anthropology (Henrich et al.).','Foundational data point for bounded rationality research.']}),

  kb('centipede','Centipede Game',['centipede'],
    'A multi-stage game where backward induction predicts immediate termination despite cooperative gains.',{
    def:['Players alternate; at each node a player can Take (ending the game) or Pass. Taking earlier yields a larger share; the pot grows if both Pass.',
         'Backward induction: the last mover Takes, so the previous mover Takes, unraveling back to the first node.'],
    int:['Rational backward induction predicts immediate Take; experiments show extensive cooperation until near the end.',
         'Challenges the plausibility of common knowledge of rationality in long chains.'],
    ex:['McKelvey-Palfrey (1992) found roughly half of subjects continued past the midpoint, contradicting the SPE prediction.',
        'Rosenthal\'s original centipede has rapidly escalating payoffs making the paradox sharp.'],
    form:['SPE is the unique backward-induction outcome; level-$k$ and quantal-response models rationalize observed behavior.',
          'Epistemic analyses show that $n$-fold common knowledge of rationality fails at long horizons.'],
    app:['Teaches the empirical limits of backward induction and motivates bounded-rationality refinements.','Widely used in experimental economics labs.']}),

  kb('public_goods','Public-Goods Game',['public good','voluntary contribution'],
    'A game in which individuals contribute to a shared good; the efficient outcome is not individually rational.',{
    def:['Each of $n$ players contributes $c_i\\in[0,w]$; public-good value is $\\alpha\\sum_j c_j/n$ for $\\alpha\\in(1,n)$; payoff $u_i=w-c_i+\\alpha\\sum_j c_j/n$.',
         'Nash equilibrium has $c_i=0$; the efficient outcome has $c_i=w$ for all.'],
    int:['Free-riding is individually rational but collectively suboptimal.',
         'A multiplayer generalization of the Prisoner\'s Dilemma.'],
    ex:['Voluntary-contribution experiments (Isaac-Walker) typically show $40$-$60$% contribution decaying toward zero without punishment.',
        'Punishment opportunities sustain cooperation (Fehr-Gächter).'],
    form:['Socially optimal contribution: $\\sum c_i^*=nw$; Nash: $c_i=0$. The efficiency gap scales with $\\alpha$ and $n$.',
          'Linter-Samuelson condition characterizes optimal public-good provision: sum of MRS equals MRT.'],
    app:['Climate-change cooperation, open-source software, and team production.','Motivates institutions for monitoring and sanctioning free-riders.']}),

  kb('tragedy_commons','Tragedy of the Commons',['commons','common pool'],
    'Overuse of a shared resource when individual users ignore the externality they impose on others.',{
    def:['Each of $n$ users chooses effort $e_i$; resource yield is $f(E)=\\sum_i e_i g(E)$ for aggregate $E=\\sum_j e_j$ with diminishing productivity.',
         'Nash equilibrium yields $E^{NE}>E^*$; the social optimum demands $f\'(E^*)=\\text{marginal cost}$ accounting for externalities.'],
    int:['Each user considers only their own gain, ignoring the cost imposed on others through depletion.',
         'Privately rational behavior aggregates into collective ruin.'],
    ex:['Overfishing in international waters and groundwater depletion are classic examples.',
        'Traffic congestion is a commons-like equilibrium with excessive driving.'],
    form:['Equivalent to a public-bad game; Pigouvian taxation internalizes the externality to implement the social optimum.',
          'Ostrom (1990) documented real-world governance institutions that sustain cooperation without privatization.'],
    app:['Environmental policy, congestion pricing, and spectrum management.','Foundational concept in environmental economics.']}),

  kb('signaling','Signaling Games',['signaling','spence'],
    'Dynamic incomplete-information games where an informed sender chooses a signal that a receiver observes.',{
    def:['Sender of type $\\theta\\in\\Theta$ chooses signal $m\\in M$; receiver observes $m$ and chooses action $a\\in A$. Payoffs $u_S(m,a,\\theta)$, $u_R(m,a,\\theta)$; prior $p(\\theta)$.',
         'Solution concepts: separating, pooling, and semi-separating perfect Bayesian equilibria.'],
    int:['The informed party conveys information through costly action choices.',
         'Equilibria are sustained by receiver beliefs that make deviation unprofitable for the sender.'],
    ex:['Spence (1973): education signals worker ability; separating equilibria have high-ability workers study more than low-ability workers would.',
        'Costly signaling in biology (peacock tails) — the handicap principle.'],
    form:['Intuitive criterion (Cho-Kreps) refines PBE by restricting off-path beliefs.',
          'Single-crossing / Spence-Mirrlees condition guarantees a unique separating equilibrium.'],
    app:['Job-market signaling, advertising, political posturing, and warranty design.','Central in information economics and biology.']}),

  kb('screening','Screening Games',['screening','rothschild stiglitz'],
    'Games where an uninformed principal offers a menu of contracts to sort informed agents.',{
    def:['Principal offers menu $\\{(q_\\theta,t_\\theta)\\}_{\\theta\\in\\Theta}$ satisfying IC ($\\theta$ prefers $(q_\\theta,t_\\theta)$ to any other item) and IR.',
         'In Rothschild-Stiglitz insurance screening, high-risk types take full insurance and low-risk types accept partial coverage.'],
    int:['The principal designs offers so that each type self-selects into a contract that reveals its type.',
         'Incentive-compatibility and participation constraints shape the menu.'],
    ex:['Airline fare classes (fully refundable vs. non-refundable) screen business vs. leisure travelers.',
        'Quantity discounts screen heavy vs. light users.'],
    form:['Taxation principle: any incentive-compatible allocation can be implemented through a price schedule, reducing screening to nonlinear pricing design.',
          'Mussa-Rosen and Maskin-Riley derive optimal screening menus under single-crossing.'],
    app:['Insurance, second-degree price discrimination, optimal income taxation (Mirrlees), and credit rationing.','Dual of signaling — the uninformed party moves first.']}),

  kb('principal_agent','Principal-Agent Problem',['agency','moral hazard','hidden action'],
    'A contracting problem where an agent\'s action is unobservable to the principal.',{
    def:['Principal chooses contract $w(y)$ based on observable output $y$; agent privately chooses effort $e$ affecting the distribution $F(y\\mid e)$ at cost $c(e)$.',
         'The problem is $\\max_{w,e}\\mathbb E[y-w(y)]$ s.t.\\ IC ($e\\in\\arg\\max_{e\'}\\mathbb E u(w)-c(e\')$) and IR ($\\mathbb E u(w)-c(e)\\ge \\bar u$).'],
    int:['Effort must be induced through output-contingent compensation that balances risk-sharing and incentives.',
         'Information asymmetry requires trading off insurance for motivation.'],
    ex:['CEO compensation via stock options aligns manager and shareholder incentives but imposes risk.',
        'Sharecropping (Stiglitz) splits output to induce effort when labor is unobservable.'],
    form:['Mirrlees-Holmström first-order approach: $1/u\'(w(y))=\\lambda+\\mu\\,\\partial\\ln f(y\\mid e)/\\partial e$ (informativeness principle).',
          'Holmström (1979): any informative signal should be incorporated into the optimal contract.'],
    app:['Executive pay, procurement contracts, insurance, and regulation.','Cornerstone of contract theory.']}),

  kb('folk','Folk Theorem',['folk theorem','repeated games folk'],
    'Any individually rational feasible payoff can be sustained in an infinitely repeated game with patient enough players.',{
    def:['Let $V$ be the convex hull of stage-game payoffs and $\\underline v_i=\\min_{\\sigma_{-i}}\\max_{\\sigma_i}u_i(\\sigma_i,\\sigma_{-i})$ (min-max). Any $v\\in V$ with $v_i>\\underline v_i$ is a subgame-perfect equilibrium payoff for $\\delta$ close enough to $1$.',
         'Perfect Folk Theorem (Fudenberg-Maskin) handles the full-dimension and imperfect-monitoring cases.'],
    int:['Patience lets players threaten long-run punishments that sustain cooperation today.',
         'Almost anything is an equilibrium — this is both a strength (explains cooperation) and weakness (weak predictions) of repeated games.'],
    ex:['In repeated Prisoner\'s Dilemma, grim-trigger sustains $(R,R)$ for $\\delta\\ge(T-R)/(T-P)$.',
        'Aumann-Shapley (1994) provided the first characterization with observable mixed actions.'],
    form:['Classical proof constructs strategies with reward/punishment phases; requires individually rational payoffs and sufficient discount factors.',
          'Versions exist for imperfect public monitoring (Abreu-Pearce-Stacchetti) and private monitoring (Kandori).'],
    app:['Rationalizes cartel stability, relational contracts, and community enforcement.','Explains why reputation and long relationships matter.']}),

  kb('tft','Tit-for-Tat',['tft','axelrod','reciprocity'],
    'A simple reciprocal strategy — cooperate first, then mimic the opponent\'s previous action.',{
    def:['Strategy in repeated Prisoner\'s Dilemma: $a_1=C$, $a_t=a_{t-1}^{(\\text{opp})}$ for $t>1$.',
         'Niceness (never defects first), retaliation, forgiveness (single punishment), and clarity are its defining traits.'],
    int:['Simple, provocable, forgiving, and clear — the four virtues that made it win Axelrod\'s tournaments.',
         'Encourages cooperation without being exploitable by defectors.'],
    ex:['Axelrod\'s 1980 tournaments: Tit-for-Tat outperformed more complex entries in a round-robin of the repeated PD.',
        'Generous and contrite variants handle noisy environments better.'],
    form:['Supports cooperation in the infinitely repeated PD as a subgame-perfect equilibrium when $\\delta\\ge(T-R)/(T-P)$.',
          'In noisy environments TFT falls into retaliation spirals; Generous TFT (Nowak-Sigmund) repairs this.'],
    app:['Emerges in biology, diplomacy, and online reputation.','Remains a canonical benchmark in multi-agent learning.']}),

  kb('backward_induction','Backward Induction',['backward induction'],
    'Algorithm for solving finite perfect-information games by reasoning from terminal nodes back to the root.',{
    def:['Starting at terminal subgames, choose optimal actions for the moving player; propagate resulting payoffs upward to parent nodes and repeat.',
         'The resulting strategy profile is the unique subgame-perfect equilibrium in generic finite perfect-information games.'],
    int:['Think about where the game ends first, then work backward to decide the current move.',
         'It operationalizes sequential rationality.'],
    ex:['Chess (in principle, via Zermelo\'s theorem) is solved by backward induction; computationally it remains infeasible.',
        'Stackelberg competition is solved by backward induction from the follower\'s best response.'],
    form:['Zermelo (1913): every finite two-player perfect-information game with no draws has a determined outcome — either a player wins or both can force a draw.',
          'Equivalent to dynamic programming on the game tree.'],
    app:['Sequential bargaining, finite-horizon stopping problems, AI game-playing (minimax + alpha-beta pruning).','Bridge between game theory and dynamic programming.']}),

  kb('ied','Iterated Elimination of Dominated Strategies',['ieds','iesds','dominance solvable'],
    'Iteratively removing strategies that are strictly dominated.',{
    def:['Let $S_i^0=S_i$ and $S_i^{k+1}=\\{s_i\\in S_i^k:\\nexists s_i\'\\in S_i^k\\text{ s.t.\\ } s_i\'\\text{ strictly dominates } s_i\\text{ on }S_{-i}^k\\}$; iterate.',
         'A game is dominance-solvable if this process leaves a unique strategy profile.'],
    int:['Common knowledge of rationality lets us remove strictly dominated options round after round.',
         'Predicts behavior when players reason about what rational opponents would never do.'],
    ex:['The Keynesian beauty contest / "p-guessing" game is dominance-solvable with unique outcome $0$.',
        'Iterative dominance solves the traveler\'s dilemma at the minimum allowable value.'],
    form:['Iterated strict dominance preserves all Nash equilibria and yields a unique outcome independent of the order of elimination.',
          'Iterated weak dominance depends on the order and can discard Nash equilibria.'],
    app:['Solution tool in auction theory and contract design; conceptual underpinning of rationalizability.','Foundation for level-$k$ models of strategic thinking.']}),

  kb('rationalizability','Rationalizability',['rationalizable'],
    'The set of strategies surviving iterated elimination of strategies that are never a best response.',{
    def:['A strategy $s_i$ is rationalizable if it survives iterated deletion of never-best-responses, i.e., it is a best response to some belief over the surviving opponent strategies.',
         'Formally the largest fixed point of the best-response operator.'],
    int:['A strategy is rationalizable if you can construct a chain of consistent beliefs that makes it optimal.',
         'Weaker than Nash equilibrium — imposes common knowledge of rationality but not of beliefs.'],
    ex:['In a $2\\times 2$ game with a strictly dominated action, only the dominant strategy is rationalizable.',
        'In zero-sum games, rationalizable strategies coincide with minimax strategies.'],
    form:['Bernheim and Pearce (1984): rationalizability is the common-knowledge-of-rationality solution concept.',
          'In two-player games, rationalizability equals iterated strict dominance.'],
    app:['Useful for analyzing games where beliefs about equilibrium play are hard to justify.','Foundation of epistemic game theory.']}),

  kb('common_knowledge','Common Knowledge',['common knowledge','aumann'],
    'An event is common knowledge if everyone knows it, everyone knows that everyone knows it, and so on ad infinitum.',{
    def:['Formally $E$ is common knowledge if $E\\subseteq\\bigcap_{n\\ge 1}K^n E$, where $K E=\\bigcap_i K_i E$ and $K_i$ denotes player $i$\'s knowledge operator.',
         'In a Kripke model, $E$ is common knowledge at state $\\omega$ iff $E$ holds at every state reachable by the reflexive transitive closure of the agents\' accessibility relations.'],
    int:['It is the infinite tower of mutual knowledge about a fact — not just you know, but you know I know, and I know you know I know, …',
         'Small failures of this tower can dramatically change strategic outcomes.'],
    ex:['Aumann\'s "Agreeing to Disagree": common priors plus common knowledge of posteriors implies equal posteriors.',
        'The Muddy Children / Blue-Eyed Islanders puzzle hinges on common knowledge of the puzzle setup.'],
    form:['Rubinstein\'s e-mail game shows that approximate common knowledge is strictly weaker than full common knowledge.',
          'Monderer-Samet characterize common knowledge via self-evident events.'],
    app:['Foundational for epistemic game theory, speculative trade, and cryptographic coordination.','Critical in the analysis of market microstructure and information cascades.']}),

  kb('potential','Potential Games',['potential game','monderer shapley'],
    'Games where all unilateral payoff changes are captured by a single real-valued function.',{
    def:['$G$ is an exact potential game if there exists $\\Phi:S\\to\\mathbb{R}$ with $u_i(s_i\',s_{-i})-u_i(s_i,s_{-i})=\\Phi(s_i\',s_{-i})-\\Phi(s_i,s_{-i})$ for all $i,s_i,s_i\',s_{-i}$.',
         'Ordinal, weighted, and generalized-ordinal potentials relax the equality requirement.'],
    int:['Players jointly hill-climb a common function — best-response dynamics always converge.',
         'This gives potential games strong computational and learnability properties.'],
    ex:['Congestion games are exact potential games with $\\Phi(s)=\\sum_e\\sum_{k=1}^{f_e(s)}c_e(k)$ (Rosenthal 1973).',
        'Coordination games on graphs are (weighted) potential games.'],
    form:['Monderer-Shapley (1996): every finite potential game has a pure Nash equilibrium — the maximizer of $\\Phi$.',
          'Better-response and fictitious-play dynamics converge to Nash in potential games.'],
    app:['Routing, load balancing, distributed optimization, and multi-agent learning.','Bridge to convex optimization via $\\Phi$.']}),

  kb('congestion','Congestion Games',['congestion','rosenthal','routing games'],
    'Games where each player\'s payoff depends on the load each facility carries.',{
    def:['Players choose subsets of facilities $E$; payoff $u_i(s)=-\\sum_{e\\in s_i}c_e(f_e(s))$ where $f_e(s)$ is the number of players using $e$.',
         'Nonatomic (continuous flow) and atomic (discrete) variants yield Wardrop and Nash equilibria respectively.'],
    int:['Every facility\'s cost depends only on its total usage, not on who uses it.',
         'Always a potential game, so pure equilibria always exist.'],
    ex:['Selfish routing on Pigou\'s network shows the Price of Anarchy $=4/3$ for linear latencies (Roughgarden-Tardos).',
        'Job scheduling on identical machines is a congestion game.'],
    form:['Rosenthal (1973): every congestion game has the exact potential $\\Phi(s)=\\sum_e\\sum_{k=1}^{f_e(s)}c_e(k)$, hence a pure Nash equilibrium.',
          'Beckmann-McGuire-Winsten variational formulation gives Wardrop equilibrium as a convex program.'],
    app:['Internet routing (BGP), transportation planning, load balancing in data centers, and cloud resource allocation.','Core in algorithmic game theory.']}),

  kb('poa','Price of Anarchy',['poa','price of anarchy'],
    'The worst-case ratio between the social cost of a Nash equilibrium and the social optimum.',{
    def:['$\\mathrm{PoA}(G)=\\dfrac{\\max_{s\\in NE(G)} \\mathrm{cost}(s)}{\\min_{s}\\mathrm{cost}(s)}$ for cost-minimization games.',
         'Price of Stability uses $\\min_{s\\in NE(G)}$ instead.'],
    int:['Quantifies how much efficiency is lost due to selfish (non-cooperative) behavior.',
         'Bounded PoA justifies decentralized design choices.'],
    ex:['For nonatomic selfish routing with linear latencies, PoA $=4/3$ (Pigou network is tight).',
        'For atomic congestion games with linear costs, PoA $=5/2$ (Awerbuch-Azar-Epstein; Christodoulou-Koutsoupias).'],
    form:['Roughgarden\'s smoothness framework yields robust PoA bounds across many solution concepts (mixed, correlated, coarse-correlated).',
          'Tight bounds often stem from Pigou-like example graphs.'],
    app:['Network routing, auctions (GSP has PoA bounded), scheduling, and facility-location games.','Key metric in algorithmic game theory.']}),

  kb('zermelo','Zermelo\'s Theorem',['zermelo'],
    'In finite two-player zero-sum games of perfect information without chance and draws allowed, either one player has a winning strategy or both can force a draw.',{
    def:['For finite two-player zero-sum games of perfect information with only two outcomes (win/lose), exactly one player has a winning strategy.',
         'With draws allowed, either one side wins or both can secure at least a draw.'],
    int:['Determinacy of perfect-information games — someone is guaranteed a good outcome.',
         'Historically the founding result of game theory (Zermelo 1913).'],
    ex:['Chess: either White wins, Black wins, or both can force a draw — the game is determined, though we do not know which case.',
        'Nim and other impartial games are fully solved (Sprague-Grundy theorem).'],
    form:['Proved by backward induction on the finite game tree.',
          'Generalized to infinite games by Martin\'s Borel Determinacy Theorem.'],
    app:['Conceptual foundation for game-playing AI and combinatorial game theory.','Basis for alpha-beta pruning and minimax search.']}),

  kb('harsanyi','Harsanyi Transformation',['harsanyi doctrine','type space transformation'],
    'Transforms games of incomplete information into games of imperfect information via a type space.',{
    def:['An incomplete-information game is reformulated as a Bayesian game $\\langle N,\\{\\Theta_i\\},p,\\{A_i\\},\\{u_i\\}\\rangle$ with Nature drawing types $\\theta\\sim p$ and revealing $\\theta_i$ to player $i$.',
         'Under the common-prior assumption, all players share $p$; heterogeneous priors yield generalized Bayesian games.'],
    int:['Turns "I don\'t know what you know" into "I know the distribution of what you might know".',
         'Enables equilibrium analysis of asymmetric-information games.'],
    ex:['Auctions with privately known valuations are modeled as Bayesian games via the Harsanyi transformation.',
        'Signaling games and reputation models routinely apply it.'],
    form:['Harsanyi (1967-68) Econometrica trilogy; the common-prior assumption is often called the Harsanyi doctrine.',
          'Mertens-Zamir constructed the universal type space ensuring a canonical model exists.'],
    app:['Auction theory, insurance, finance with asymmetric information, and mechanism design.','Essential conceptual tool in modern IO and information economics.']})
];
