export const KB_VERSION = '1.0.0';
export const KB_UPDATED = '2026-05-01';

export function kb(id, name, aliases, summary, f, related=[]) {
  return { id, name, aliases: [name.toLowerCase(), ...aliases.map(a => a.toLowerCase())], summary, f, related };
}

export function entryText(e) {
  return `${e.name} ${e.aliases.join(' ')} ${e.summary} ${e.f.def.join(' ')} ${e.f.int.join(' ')} ${e.f.ex.join(' ')} ${e.f.form.join(' ')} ${e.f.app.join(' ')}`;
}

export const KB = [
  kb('house_of_wisdom','House of Wisdom',['bayt al-hikmah','house of wisdom baghdad'],
    'Major intellectual center in Abbasid Baghdad that housed a vast library and translation institute.',{
    def:['Founded in Baghdad during the reign of Caliph Harun al-Rashid (r. 786–809) and expanded by his son al-Ma\'mun (r. 813–833).',
         'Served as a translation bureau, library, and academy where Greek, Persian, Indian, and Syriac texts were translated into Arabic.'],
    int:['It was the intellectual heart of the Islamic Golden Age — a place where knowledge from all civilizations was gathered, translated, critiqued, and expanded.',
         'The House of Wisdom embodied the Abbasid commitment to knowledge: "The ink of the scholar is holier than the blood of the martyr."'],
    ex:['Hunayn ibn Ishaq and his team translated nearly all of Galen\'s medical works and much of Aristotle there.',
         'Al-Khwarizmi worked at the House of Wisdom, producing his foundational works on algebra and astronomy.'],
    form:['The translation movement followed systematic methods: a scholar would translate from Greek to Syriac, then a native Arabic speaker would render it into clear Arabic prose.',
          'The library\'s catalog reportedly filled forty volumes, indicating a collection of hundreds of thousands of manuscripts.'],
    app:['Its model influenced later institutions like the House of Knowledge in Cairo and the translation schools of Toledo.',
         'Demonstrated that state-sponsored knowledge production accelerates scientific and cultural advancement.']},
   ['al_khwarizmi','al_kindi','translation_movement','mamun']),

  kb('al_khwarizmi','Al-Khwarizmi',['al-khwarizmi','algoritmi','muhammad ibn musa'],
    'Persian mathematician, astronomer, and geographer whose works founded algebra and introduced algorithms.',{
    def:['Muhammad ibn Musa al-Khwarizmi (c. 780–850) was a scholar at the House of Wisdom in Baghdad.',
         'His name gave rise to the word "algorithm" and his book "Al-Kitab al-Mukhtasar fi Hisab al-Jabr wa\'l-Muqabala" gave us "algebra."'],
    int:['He synthesized Greek geometry with Indian numerals and Persian mathematics to create entirely new fields.',
         'His approach was revolutionary: reduce problems to standard forms, then apply systematic solution procedures.'],
    ex:['He solved linear and quadratic equations by completing the square — a method still taught today.',
         'His work on Hindu-Arabic numerals (translated into Latin as "Algoritmi de numero Indorum") introduced the decimal positional system to Europe.'],
    form:['Al-Jabr ("restoration") referred to moving subtracted terms to the other side of an equation; al-Muqabala ("balancing") meant canceling equal terms on both sides.',
          'He classified quadratic equations into six canonical forms since negative coefficients were not yet accepted.'],
    app:['Algebra became the foundation of all subsequent mathematics, from Renaissance algebra to modern abstract algebra.',
         'His geographical work corrected Ptolemy\'s maps and influenced cartography for centuries.']},
   ['house_of_wisdom','algebra','al_kindi','ibn_sina']),

  kb('algebra','Algebra',['al-jabr','algebra history','origin of algebra'],
    'Mathematical discipline founded by Al-Khwarizmi for solving equations through systematic transformation.',{
    def:['The word "algebra" comes from "al-jabr" in Al-Khwarizmi\'s 9th-century treatise on equation solving.',
         'Originally the art of restoring balance in equations by moving terms from one side to another.'],
    int:['Before algebra, mathematics was largely geometric. Algebra introduced symbolic manipulation as a tool for solving unknowns.',
         'It transformed mathematics from a collection of specific solutions into a general method applicable to entire classes of problems.'],
    ex:['Al-Khwarizmi solved "a square and ten roots equal thirty-nine" (x² + 10x = 39) by completing the square to get x = 3.',
         'Omar Khayyam later extended algebra to cubic equations using geometric constructions of conic sections.'],
    form:['Al-Khwarizmi\'s six canonical forms: $ax^2=bx$, $ax^2=c$, $bx=c$, $ax^2+bx=c$, $ax^2+c=bx$, $bx+c=ax^2$.',
          'Solutions were expressed rhetorically (in words), not symbolically — symbolic algebra came much later with Viète and Descartes.'],
    app:['Algebra underlies all of modern science, engineering, economics, and computer science.',
         'The abstraction of "unknown quantities" enabled everything from physics equations to cryptographic algorithms.']},
   ['al_khwarizmi','omar_khayyam','ibn_sina']),

  kb('al_kindi','Al-Kindi',['al-kindus','philosopher of the arabs','yaqub ibn ishaq'],
    'First major Islamic philosopher who synthesized Greek philosophy with Islamic thought.',{
    def:['Abu Yusuf Ya\'qub ibn Ishaq al-Kindi (c. 801–873) was a polymath known as "the Philosopher of the Arabs."',
         'He directed the translation movement at the House of Wisdom and wrote original works on philosophy, optics, medicine, and cryptography.'],
    int:['Al-Kindi believed that truth could not contradict truth — Greek philosophy and Islamic revelation must ultimately agree.',
         'He pioneered the idea that knowledge is universal and belongs to no single civilization.'],
    ex:['His work "On First Philosophy" introduced Aristotelian metaphysics to the Islamic world.',
         'He wrote the earliest known book on cryptography, describing frequency analysis for breaking substitution ciphers.'],
    form:['He argued that the universe had a beginning in time (against Aristotle\'s eternity), using arguments that later influenced Aquinas.',
          'In optics, he correctly explained vision as rays entering the eye, not emanating from it.'],
    app:['His synthesis of Greek and Islamic thought laid groundwork for Al-Farabi, Avicenna, and Averroes.',
         'His cryptographic methods anticipated modern cryptanalysis by a millennium.']},
   ['house_of_wisdom','al_khwarizmi','ibn_sina','translation_movement']),

  kb('ibn_sina','Ibn Sina (Avicenna)',['avicenna','ibn sina','abu ali al-husayn'],
    'Persian polymath whose "Canon of Medicine" was the standard medical text in Europe and the Islamic world for 600 years.',{
    def:['Abu Ali al-Husayn ibn Abdullah ibn Sina (980–1037), known in the West as Avicenna, was a Persian polymath.',
         'He wrote 450 works across philosophy, medicine, astronomy, logic, and psychology; about 240 survive.'],
    int:['Ibn Sina systematized all of Greek medical knowledge and added his own clinical observations into a single coherent framework.',
         'His "Floating Man" thought experiment anticipated Descartes\' "Cogito" by six centuries.'],
    ex:['The Canon of Medicine described contagious diseases, quarantine, clinical trials, and the effects of diet and environment on health.',
         'His "Book of Healing" was a philosophical and scientific encyclopedia covering logic, physics, mathematics, and metaphysics.'],
    form:['The Canon organized medicine into: general principles, simple drugs (materia medica), diseases by body part, systemic conditions, and compound remedies.',
          'He distinguished mediastinitis from pleurisy and described over 700 drugs with their properties and dosages.'],
    app:['The Canon was translated into Latin in the 12th century and remained a required text at European medical schools until the 1650s.',
         'His distinction between essence and existence influenced both Islamic and Christian scholastic philosophy.']},
   ['al_razI','al_khwarizmi','ibn_al_haytham','canon_of_medicine']),

  kb('canon_of_medicine','Canon of Medicine',['al-qanun fi al-tibb','avicenna canon'],
    'Ibn Sina\'s medical encyclopedia that systematized all known medical knowledge and remained authoritative for six centuries.',{
    def:['Written by Ibn Sina (Avicenna) around 1025 CE, the Canon (Al-Qanun fi al-Tibb) spans five books and over a million words.',
         'It synthesized Greek (Hippocrates, Galen), Persian, Indian, and Arabic medical knowledge into a unified system.'],
    int:['The Canon treated medicine as a rational science based on observation and logic, not superstition.',
         'It introduced concepts like clinical trials, quarantine, and evidence-based practice centuries before they appeared in Europe.'],
    ex:['Book I covers general principles: anatomy, physiology, pathology, diagnosis, and treatment.',
         'Book II describes 760 simple drugs; Book III covers diseases by organ; Book IV covers systemic diseases; Book V covers compound remedies.'],
    form:['The humoral theory organized health as balance of four humors (blood, phlegm, yellow bile, black bile) corresponding to four qualities (hot, cold, wet, dry).',
          'Pulse diagnosis classified pulses by rate, rhythm, amplitude, and regularity — a sophisticated diagnostic tool.'],
    app:['Translated to Latin by Gerard of Cremona in the 12th century, it became the standard medical textbook at Montpellier, Leuven, and other European universities.',
         'Its emphasis on systematic observation and classification influenced the development of modern clinical medicine.']},
   ['ibn_sina','al_razI','medicine']),

  kb('ibn_al_haytham','Ibn al-Haytham (Alhazen)',['alhazen','ibn al-haytham','hasan ibn al-haytham'],
    'Arab scientist who founded optics as an experimental science and pioneered the scientific method.',{
    def:['Abu Ali al-Hasan ibn al-Hasan ibn al-Haytham (965–1040), known in the West as Alhazen, was an Arab polymath.',
         'His "Book of Optics" (Kitab al-Manazir) revolutionized understanding of light, vision, and scientific methodology.'],
    int:['He was the first to prove that vision occurs when light enters the eye, not when rays emanate from it (refuting Euclid and Ptolemy).',
         'He established that scientific theories must be proven through repeatable experiments — the birth of the experimental method.'],
    ex:['He used the camera obscura to prove that light travels in straight lines.',
         'He explained rainbows, atmospheric refraction, and twilight through careful observation and experimentation.'],
    form:['His method: observe a phenomenon, propose a hypothesis, design experiments to test it, analyze results mathematically, and draw conclusions.',
          'He studied spherical and parabolic mirrors, lens aberration, and magnification — laying groundwork for telescopes and microscopes.'],
    app:['His optics influenced Kepler, Descartes, Newton, and the entire European scientific revolution.',
         'His experimental method prefigured the modern scientific method by 600 years.']},
   ['optics','camera_obscura','scientific_method','al_razI']),

  kb('optics','Optics in the Golden Age',['ilm al-manazir','golden age optics'],
    'The science of light and vision as developed by Golden Age scholars, founded by Ibn al-Haytham.',{
    def:['"Ilm al-Manazir" (science of vision) was transformed from Greek speculation into an experimental science by Ibn al-Haytham.',
         'It studied light propagation, reflection, refraction, lenses, mirrors, and the anatomy of the eye.'],
    int:['Greek optics held that vision worked by rays shooting out of the eyes. Ibn al-Haytham proved the opposite: light enters the eye from objects.',
         'This reversal was as revolutionary as Copernicus placing the Sun instead of Earth at the center.'],
    ex:['Ibn al-Haytham correctly explained moonlight as reflected sunlight and analyzed the apparent enlargement of the moon at the horizon.',
         'Kamal al-Din al-Farisi later used Ibn al-Haytham\'s work to give the first correct explanation of the rainbow.'],
    form:['The law of refraction was studied empirically; Ibn Sahl (984) described what we now call Snell\'s law for lens design.',
          'The camera obscura demonstrated that light travels in straight lines and forms inverted images through small apertures.'],
    app:['Optical knowledge enabled eyeglasses, telescopes, microscopes, and cameras — tools that transformed science.',
         'Ibn al-Haytham\'s Latin works influenced Roger Bacon, Witelo, and Kepler directly.']},
   ['ibn_al_haytham','camera_obscura','ibn_sahl']),

  kb('translation_movement','Translation Movement',['graeco-arabic translation','translation movement abbasid'],
    'Massive project to translate Greek, Persian, Indian, and Syriac scientific works into Arabic.',{
    def:['Beginning in the 8th century under the Abbasids, scholars translated the scientific heritage of antiquity into Arabic.',
         'The movement was state-sponsored, with caliphs paying translators their weight in gold.'],
    int:['It was the largest knowledge-transfer project in human history — preserving works that would have been lost and expanding them.',
         'Without this movement, much of Greek science and philosophy would have been lost to humanity.'],
    ex:['Hunayn ibn Ishaq alone translated nearly all of Galen\'s works, plus Aristotle, Plato, and Hippocrates.',
         'Indian astronomical tables (the Sindhind) and the decimal numeral system were translated and adopted.'],
    form:['Translation was systematic: teams of scholars fluent in Greek/Syriac and Arabic worked together for accuracy.',
          'Translators developed Arabic scientific terminology from scratch — words like "algebra," "algorithm," and "alkali" entered via this process.'],
    app:['The translated works became the foundation for original Islamic scholarship, which later flowed back to Europe via Toledo and Sicily.',
         'The translation movement established Arabic as the lingua franca of science for 500 years.']},
   ['house_of_wisdom','al_kindi','hunayn_ibn_ishaq']),

  kb('al_razI','Al-Razi (Rhazes)',['rhazes','al-razi','muhammad ibn zakariya'],
    'Persian physician and alchemist who distinguished smallpox from measles and pioneered clinical observation.',{
    def:['Abu Bakr Muhammad ibn Zakariya al-Razi (c. 854–925), known in the West as Rhazes, was a Persian polymath.',
         'He was director of the Baghdad hospital and wrote over 200 works on medicine, alchemy, and philosophy.'],
    int:['Al-Razi was the first to distinguish smallpox from measles as distinct diseases with different symptoms and courses.',
         'He emphasized clinical observation over theoretical speculation — a proto-scientific approach to medicine.'],
    ex:['He chose the site for Baghdad\'s hospital by hanging pieces of meat in different districts and selecting where decomposition was slowest.',
         'His "Comprehensive Book on Medicine" (al-Hawi) was a 23-volume medical encyclopedia based on case studies.'],
    form:['He classified diseases by symptoms and progression, not by humoral theory alone.',
          'In alchemy, he classified substances into mineral, vegetable, and animal, and described distillation and crystallization techniques.'],
    app:['Al-Hawi was translated into Latin as "Continens" and became a foundational medical text in medieval Europe.',
         'His emphasis on observation and experimentation influenced later physicians including Ibn Sina.']},
   ['ibn_sina','canon_of_medicine','medicine','alchemy']),

  kb('astrolabe','Astrolabe',['astronomical astrolabe','islamic astrolabe'],
    'Sophisticated astronomical instrument for solving problems relating to time, position, and celestial motion.',{
    def:['A planar projection instrument consisting of a mater (body), rete (star map), plates (climate-specific projections), and alidade (sighting rule).',
         'Could determine time, latitude, prayer directions, and planetary positions from stellar observations.'],
    int:['The astrolabe was the smartphone of the medieval world — a portable analog computer for astronomy, navigation, and timekeeping.',
         'Islamic scholars perfected the astrolabe, adding universal plates and spherical projections.'],
    ex:['Al-Zarqali\'s saphea astrolabe worked at any latitude without changing plates.',
         'Nasir al-Din al-Tusi\'s astrolabe incorporated his mathematical innovations for more accurate calculations.'],
    form:['The stereographic projection from the south pole onto the equatorial plane preserved angles, making the astrolabe mathematically precise.',
          'The shadow square on the back enabled height and distance calculations using trigonometry.'],
    app:['Astrolabes enabled navigation across the Indian Ocean and later the Atlantic.',
         'They were essential for determining prayer times and the qibla direction across the Islamic world.']},
   ['astronomy','al_zarqali','nasir_al_din_tusi']),

  kb('astronomy','Astronomy in the Golden Age',['ilm al-falak','islamic astronomy'],
    'Highly advanced astronomical science developed in the Islamic world, combining Greek, Persian, and Indian traditions.',{
    def:['Islamic astronomers built observatories, compiled precise star catalogs, and refined planetary models.',
         'They corrected Ptolemy\'s Almagest, calculated the length of the solar year to remarkable accuracy, and named most visible stars.'],
    int:['Astronomy was both a practical science (for prayer times, qibla, calendar) and a theoretical pursuit (planetary models).',
         'The Maragha school\'s mathematical innovations directly influenced Copernicus.'],
    ex:['Al-Battani calculated the solar year as 365.24255 days (modern value: 365.24219).',
         'The Ulugh Beg Observatory in Samarkand produced a star catalog of 1,018 stars with unprecedented accuracy.'],
    form:['The Tusi couple — a mathematical device where a small circle rolls inside a larger one — resolved Ptolemaic inconsistencies.',
          'Equatorium instruments mechanically solved the equations of planetary motion.'],
    app:['Star names like Aldebaran, Altair, Betelgeuse, Rigel, and Vega all derive from Arabic.',
         'Astronomical tables (zij) were used for navigation and calendar calculation across three continents.']},
   ['astrolabe','al_battani','maragha_school','ulugh_beg']),

  kb('algebra_development','Development of Algebra',['history of algebra','algebra evolution'],
    'The evolution of algebra from Al-Khwarizmi\'s rhetorical algebra to symbolic notation.',{
    def:['Algebra evolved through three stages: rhetorical (words only), syncopated (abbreviations), and symbolic (modern notation).',
         'Islamic scholars carried algebra from geometric problem-solving to a general theory of equations.'],
    int:['Al-Khwarizmi\'s algebra was rhetorical — equations written entirely in words. "A square and ten roots equal thirty-nine."',
         'Omar Khayyam classified and solved cubic equations geometrically; al-Karaji began arithmetizing algebra.'],
    ex:['Thabit ibn Qurra gave a general proof for amicable numbers using algebraic reasoning.',
         'Al-Samawal\'s work on polynomial division anticipated modern algebra by centuries.'],
    form:['The six canonical forms of Al-Khwarizmi were gradually reduced as negative numbers gained acceptance.',
          'The fundamental theorem of algebra (every polynomial has a root) was conjectured but not proven until Gauss.'],
    app:['Algebra became the language of all quantitative science.',
         'The abstraction from specific numbers to general symbols enabled modern mathematics and physics.']},
   ['al_khwarizmi','omar_khayyam','algebra']),

  kb('maragha_school','Maragha School',['maragheh observatory','tusi couple'],
    'School of astronomers at the Maragha Observatory who developed alternatives to Ptolemaic astronomy.',{
    def:['Founded by Nasir al-Din al-Tusi in 1259 in northwestern Persia, the Maragha school produced revolutionary astronomical models.',
         'The observatory housed a library of 400,000 volumes and instruments including a 6-meter sextant.'],
    int:['The Tusi couple — two circles where one rolls inside the other — generated linear motion from circular motion.',
         'This resolved a key problem in Ptolemy\'s models and influenced Copernicus directly.'],
    ex:['Al-Tusi\'s planetary models eliminated the equant point that violated uniform circular motion.',
         'Ibn al-Shatir\'s models for the Moon and planets were mathematically identical to Copernicus\' later models.'],
    form:['The Maragha school\'s innovations: universal solutions replacing ad-hoc Ptolemaic devices, physical reality as criterion, mathematical consistency.',
          'Copernicus likely encountered these ideas through Byzantine Greek translations circulating in Italy.'],
    app:['The Maragha school bridged Islamic and European astronomy — their models directly influenced the Copernican revolution.',
         'The observatory model influenced later institutions like Ulugh Beg\'s Samarkand observatory and Tycho Brahe\'s Uraniborg.']},
   ['astronomy','nasir_al_din_tusi','ibn_al_shatir']),

  kb('paper_making','Paper Making',['paper islam','spread of paper'],
    'Introduction and spread of papermaking technology from China through the Islamic world to Europe.',{
    def:['Papermaking reached the Islamic world after the Battle of Talas (751), where Chinese prisoners revealed the technique.',
         'By 800, paper mills operated in Baghdad, Damascus, Cairo, Cordoba, and Fez.'],
    int:['Paper was cheaper and more durable than parchment, enabling mass production of books and democratizing knowledge.',
         'The paper revolution made the translation movement and the flourishing of libraries possible.'],
    ex:['Baghdad had over 100 paper mills by 900 CE.',
         'The library of Tripoli reportedly held 3 million volumes before its destruction in 1109.'],
    form:['Islamic papermakers improved Chinese techniques: linen and hemp fibers, starch sizing, watermarks.',
          'The codex form (bound pages) replaced scrolls, enabling random access to text.'],
    app:['Paper enabled the proliferation of books, libraries, and literacy across the Islamic world.',
         'Paper reached Europe via Islamic Spain in the 12th century, enabling the Renaissance and printing press.']},
   ['house_of_wisdom','translation_movement']),

  kb('ibn_rushd','Ibn Rushd (Averroes)',['averroes','ibn rushd'],
    'Andalusian philosopher and jurist whose commentaries on Aristotle shaped medieval European thought.',{
    def:['Abu al-Walid Muhammad ibn Ahmad ibn Rushd (1126–1198), known as Averroes, was an Andalusian polymath.',
         'He wrote extensive commentaries on Aristotle that became standard texts in European universities.'],
    int:['Ibn Rushd argued that philosophy and religion were two paths to the same truth — reason and revelation cannot contradict.',
         'His "incompatibility of incompatibility" argued that apparent conflicts between philosophy and scripture arise from misinterpretation.'],
    ex:['His "Tahafut al-Tahafut" (Incoherence of the Incoherence) defended philosophy against Al-Ghazali\'s critiques.',
         'His medical work "Al-Kulliyat" (Colliget) was a comprehensive medical encyclopedia used in Europe.'],
    form:['He distinguished three levels of discourse: rhetorical (for masses), dialectical (for theologians), demonstrative (for philosophers).',
          'His concept of "unity of the intellect" influenced Latin Averroism and debates at the University of Paris.'],
    app:['"The Commentator" (as he was known in Latin) shaped Aquinas, Maimonides, and all of medieval scholasticism.',
         'Averroism became a major intellectual movement in 13th-century Europe.']},
   ['al_ghazali','ibn_sina','philosophy']),

  kb('al_ghazali','Al-Ghazali',['algazel','abu hamid al-ghazali'],
    'Influential Islamic theologian, jurist, and mystic who critiqued excessive rationalism in philosophy.',{
    def:['Abu Hamid Muhammad al-Ghazali (1058–1111) was a Persian theologian and Sufi mystic.',
         'His "Incoherence of the Philosophers" critiqued Neoplatonic philosophy\'s claims to certain knowledge.'],
    int:['Al-Ghazali did not reject reason itself but argued that philosophical metaphysics overstepped its bounds.',
         'His spiritual crisis and turn to Sufism produced one of the most influential works of Islamic spirituality.'],
    ex:['He identified 20 points where philosophers contradicted Islamic doctrine, particularly on the eternity of the world and God\'s knowledge of particulars.',
         'His "Revival of the Religious Sciences" synthesized jurisprudence, theology, and mysticism.'],
    form:['His critique targeted the Neoplatonic emanation theory and the philosophers\' claim of necessary causal connections.',
          'He argued that causation is habitual, not necessary — anticipating Hume\'s critique of causation by 600 years.'],
    app:['His work prompted responses from Ibn Rushd and shaped the boundaries between philosophy and theology.',
         'His spiritual writings remain among the most influential in Islamic thought.']},
   ['ibn_rushd','ibn_sina','philosophy']),

  kb('medicine_golden_age','Medicine in the Golden Age',['tibb','islamic medicine'],
    'Medical science as practiced and advanced in the Islamic world, combining Greek theory with clinical observation.',{
    def:['Islamic medicine synthesized Hippocratic-Galenic theory with Persian, Indian, and original clinical observations.',
         'Hospitals (bimaristans) were established across the Islamic world as centers of treatment and teaching.'],
    int:['Medicine was professionalized: physicians required licenses, pharmacies were regulated, and hospitals had wards for different diseases.',
         'The concept of "first, do no harm" and evidence-based practice were central.'],
    ex:['Al-Razi distinguished smallpox from measles; Ibn al-Nafis described pulmonary circulation 300 years before Harvey.',
         'Al-Zahrawi\'s surgical encyclopedia described over 200 surgical instruments, many invented by him.'],
    form:['Medical education required studying anatomy, physiology, pathology, pharmacology, and clinical practice.',
          'Hospitals like Al-Mansuri in Cairo had separate wards, pharmacies, libraries, and lecture halls.'],
    app:['Islamic medical texts remained standard in Europe for centuries after the Renaissance.',
         'Modern medical ethics, licensing, and hospital organization owe much to Islamic models.']},
   ['ibn_sina','al_razI','canon_of_medicine','al_zahrawi']),

  kb('al_biruni','Al-Biruni',['biruni','abu rayhan'],
    'Persian scholar who made groundbreaking contributions to astronomy, geography, and comparative religion.',{
    def:['Abu Rayhan Muhammad ibn Ahmad al-Biruni (973–1048) was a Persian polymath.',
         'He calculated Earth\'s radius with remarkable accuracy and wrote extensively on India\'s sciences and culture.'],
    int:['Al-Biruni was arguably the first anthropologist — he studied cultures objectively without imposing his own biases.',
         'His scientific method emphasized repeated observation, measurement, and cross-verification.'],
    ex:['He calculated Earth\'s radius as 6,339 km (modern: 6,371 km) using a mountain height and horizon dip angle.',
         'His "India" (Tarikh al-Hind) described Indian mathematics, astronomy, religion, and customs with remarkable objectivity.'],
    form:['He discussed whether the Earth rotates on its axis, noting that observable phenomena would be the same either way.',
          'He compiled astronomical tables and described the astrolabe with mathematical rigor.'],
    app:['His geographical works influenced later cartographers and explorers.',
         'His comparative approach to religion anticipated modern religious studies by a millennium.']},
   ['astronomy','al_khwarizmi']),

  kb('al_zahrawi','Al-Zahrawi (Abulcasis)',['abulcasis','al-zahrawi'],
    'Andalusian surgeon whose medical encyclopedia was the standard surgical text in Europe for 500 years.',{
    def:['Abu al-Qasim Khalaf ibn al-Abbas al-Zahrawi (936–1013), known as Abulcasis, was an Andalusian physician.',
         'His "Al-Tasrif" was a 30-volume medical encyclopedia; volume 30 on surgery was especially influential.'],
    int:['Al-Zahrawi elevated surgery from a manual craft to a medical science based on anatomy and observation.',
         'He invented or described dozens of surgical instruments still recognizable today.'],
    ex:['He pioneered cauterization, ligatures for controlling bleeding, and surgical removal of bladder stones.',
         'He described procedures for cataract surgery, tooth extraction, amputation, and setting broken bones.'],
    form:['The Al-Tasrif covered: medicine, surgery, orthopedics, ophthalmology, pharmacology, nutrition, and childbirth.',
          'His illustrations of surgical instruments became the standard reference for European surgeons.'],
    app:['Translated to Latin by Gerard of Cremona, the Al-Tasrif was used at Montpellier and other European medical schools until the 16th century.',
         'Many modern surgical instruments trace their design to al-Zahrawi\'s originals.']},
   ['medicine_golden_age','al_razI','ibn_sina']),

  kb('ibn_al_nafis','Ibn al-Nafis',['ibn al-nafis','ala al-din'],
    'Arab physician who discovered pulmonary circulation 300 years before William Harvey.',{
    def:['Ala al-Din Abu al-Hasan Ibn al-Nafis (1213–1288) was an Arab physician and anatomist.',
         'He correctly described how blood flows from the right ventricle through the lungs to the left ventricle.'],
    int:['He refuted Galen\'s theory that blood passes through invisible pores in the heart septum.',
         'His discovery was not widely known in Europe until the 20th century, when his manuscript was rediscovered.'],
    ex:['"The blood is purified in the lungs, then passes from the right chamber to the left through the pulmonary artery and veins."',
         'He also described coronary circulation and capillary function.'],
    form:['His commentary on Ibn Sina\'s Canon contained his circulatory insights, which went unnoticed for centuries.',
          'He correctly stated that the heart is nourished by coronary arteries, not by blood in its chambers.'],
    app:['His work anticipated Harvey\'s complete description of systemic circulation.',
         'Modern historians recognize him as the true discoverer of pulmonary circulation.']},
   ['medicine_golden_age','ibn_sina','canon_of_medicine']),

  kb('philosophy_golden_age','Philosophy in the Golden Age',['falsafa','islamic philosophy'],
    'The philosophical tradition that synthesized Greek philosophy with Islamic theology.',{
    def:['Falsafa (philosophy) was the rationalist tradition in Islamic thought, drawing on Aristotle, Plato, and Neoplatonism.',
         'Key figures include Al-Kindi, Al-Farabi, Ibn Sina, and Ibn Rushd.'],
    int:['Philosophers argued that reason and revelation are compatible paths to truth.',
         'They developed original metaphysics, epistemology, ethics, and political philosophy.'],
    ex:['Al-Farabi\'s "Virtuous City" described an ideal state governed by philosopher-prophets.',
         'Ibn Sina\'s distinction between essence and existence influenced both Islamic and Christian scholasticism.'],
    form:['The translation of Aristotle\'s works sparked original commentary and critique, not mere repetition.',
          'The debate between rationalists (falasifa) and traditionalists (like Al-Ghazali) defined Islamic intellectual history.'],
    app:['Islamic philosophy transmitted Greek thought to medieval Europe and shaped scholasticism.',
         'Questions about faith and reason, universals, and the nature of God remain central to philosophy.']},
   ['al_kindi','ibn_sina','ibn_rushd','al_ghazali']),
];
