export const KB_VERSION = '1.1.0';
export const KB_UPDATED = '2026-05-16';

export function kb(id, name, aliases, summary, f, related=[]) {
  return { id, name, aliases: [name.toLowerCase(), ...aliases.map(a => a.toLowerCase())], summary, f, related };
}

export function entryText(e) {
  return `${e.name} ${e.aliases.join(' ')} ${e.summary} ${e.f.def.join(' ')} ${e.f.int.join(' ')} ${e.f.ex.join(' ')} ${e.f.form.join(' ')} ${e.f.app.join(' ')}`;
}

export const KB_ID_TO_INDEX = new Map(KB.map((e, i) => [e.id, i]));

export const KB = [
  kb('house_of_wisdom','House of Wisdom',['bayt al-hikmah','house of wisdom baghdad','bayt al-hikma','house of knowledge','bait al-hikmah'],
    'Major intellectual center in Abbasid Baghdad that housed a vast library and translation institute.',{
    def:['Founded in Baghdad during the reign of Caliph Harun al-Rashid (r. 786\u2013809) and expanded by his son al-Ma\'mun (r. 813\u2013833).',
         'Served as a translation bureau, library, and academy where Greek, Persian, Indian, and Syriac texts were translated into Arabic.'],
    int:['It was the intellectual heart of the Islamic Golden Age \u2014 a place where knowledge from all civilizations was gathered, translated, critiqued, and expanded.',
         'The House of Wisdom embodied the Abbasid commitment to knowledge: "The ink of the scholar is holier than the blood of the martyr."'],
    ex:['Hunayn ibn Ishaq and his team translated nearly all of Galen\'s medical works and much of Aristotle there.',
         'Al-Khwarizmi worked at the House of Wisdom, producing his foundational works on algebra and astronomy.'],
    form:['The translation movement followed systematic methods: a scholar would translate from Greek to Syriac, then a native Arabic speaker would render it into clear Arabic prose.',
          'The library\'s catalog reportedly filled forty volumes, indicating a collection of hundreds of thousands of manuscripts.'],
    app:['Its model influenced later institutions like the House of Knowledge in Cairo and the translation schools of Toledo.',
         'Demonstrated that state-sponsored knowledge production accelerates scientific and cultural advancement.']},
   ['al_khwarizmi','al_kindi','translation_movement','mamun']),

  kb('al_khwarizmi','Al-Khwarizmi',['al-khwarizmi','algoritmi','muhammad ibn musa','al khwarizmi','alkhwarizmi','khwarizmi'],
    'Persian mathematician, astronomer, and geographer whose works founded algebra and introduced algorithms.',{
    def:['Muhammad ibn Musa al-Khwarizmi (c. 780\u2013850) was a scholar at the House of Wisdom in Baghdad.',
         'His name gave rise to the word "algorithm" and his book "Al-Kitab al-Mukhtasar fi Hisab al-Jabr wa\'l-Muqabala" gave us "algebra."'],
    int:['He synthesized Greek geometry with Indian numerals and Persian mathematics to create entirely new fields.',
         'His approach was revolutionary: reduce problems to standard forms, then apply systematic solution procedures.'],
    ex:['He solved linear and quadratic equations by completing the square \u2014 a method still taught today.',
         'His work on Hindu-Arabic numerals (translated into Latin as "Algoritmi de numero Indorum") introduced the decimal positional system to Europe.'],
    form:['Al-Jabr ("restoration") referred to moving subtracted terms to the other side of an equation; al-Muqabala ("balancing") meant canceling equal terms on both sides.',
          'He classified quadratic equations into six canonical forms since negative coefficients were not yet accepted.'],
    app:['Algebra became the foundation of all subsequent mathematics, from Renaissance algebra to modern abstract algebra.',
         'His geographical work corrected Ptolemy\'s maps and influenced cartography for centuries.']},
   ['house_of_wisdom','algebra','al_kindi','ibn_sina']),

  kb('algebra','Algebra',['al-jabr','algebra history','origin of algebra','algebra origin','al-kitab al-mukhtasar'],
    'Mathematical discipline founded by Al-Khwarizmi for solving equations through systematic transformation.',{
    def:['The word "algebra" comes from "al-jabr" in Al-Khwarizmi\'s 9th-century treatise on equation solving.',
         'Originally the art of restoring balance in equations by moving terms from one side to another.'],
    int:['Before algebra, mathematics was largely geometric. Algebra introduced symbolic manipulation as a tool for solving unknowns.',
         'It transformed mathematics from a collection of specific solutions into a general method applicable to entire classes of problems.'],
    ex:['Al-Khwarizmi solved "a square and ten roots equal thirty-nine" ($x^2 + 10x = 39$) by completing the square to get $x = 3$.',
         'Omar Khayyam later extended algebra to cubic equations using geometric constructions of conic sections.'],
    form:['Al-Khwarizmi\'s six canonical forms: $ax^2=bx$, $ax^2=c$, $bx=c$, $ax^2+bx=c$, $ax^2+c=bx$, $bx+c=ax^2$.',
          'Solutions were expressed rhetorically (in words), not symbolically \u2014 symbolic algebra came much later with Vi\\`ete and Descartes.'],
    app:['Algebra underlies all of modern science, engineering, economics, and computer science.',
         'The abstraction of "unknown quantities" enabled everything from physics equations to cryptographic algorithms.']},
   ['al_khwarizmi','omar_khayyam','ibn_sina']),

  kb('al_kindi','Al-Kindi',['al-kindus','philosopher of the arabs','yaqub ibn ishaq','al kindi','alkindi','kindi'],
    'First major Islamic philosopher who synthesized Greek philosophy with Islamic thought.',{
    def:['Abu Yusuf Ya\'qub ibn Ishaq al-Kindi (c. 801\u2013873) was a polymath known as "the Philosopher of the Arabs."',
         'He directed the translation movement at the House of Wisdom and wrote original works on philosophy, optics, medicine, and cryptography.'],
    int:['Al-Kindi believed that truth could not contradict truth \u2014 Greek philosophy and Islamic revelation must ultimately agree.',
         'He pioneered the idea that knowledge is universal and belongs to no single civilization.'],
    ex:['His work "On First Philosophy" introduced Aristotelian metaphysics to the Islamic world.',
         'He wrote the earliest known book on cryptography, describing frequency analysis for breaking substitution ciphers.'],
    form:['He argued that the universe had a beginning in time (against Aristotle\'s eternity), using arguments that later influenced Aquinas.',
          'In optics, he correctly explained vision as rays entering the eye, not emanating from it.'],
    app:['His synthesis of Greek and Islamic thought laid groundwork for Al-Farabi, Avicenna, and Averroes.',
         'His cryptographic methods anticipated modern cryptanalysis by a millennium.']},
   ['house_of_wisdom','al_khwarizmi','ibn_sina','translation_movement']),

  kb('ibn_sina','Ibn Sina (Avicenna)',['avicenna','ibn sina','abu ali al-husayn','ibnsina','abu ali ibn sina','ibn sina avicenna'],
    'Persian polymath whose "Canon of Medicine" was the standard medical text in Europe and the Islamic world for 600 years.',{
    def:['Abu Ali al-Husayn ibn Abdullah ibn Sina (980\u20131037), known in the West as Avicenna, was a Persian polymath.',
         'He wrote 450 works across philosophy, medicine, astronomy, logic, and psychology; about 240 survive.'],
    int:['Ibn Sina systematized all of Greek medical knowledge and added his own clinical observations into a single coherent framework.',
         'His "Floating Man" thought experiment anticipated Descartes\' "Cogito" by six centuries.'],
    ex:['The Canon of Medicine described contagious diseases, quarantine, clinical trials, and the effects of diet and environment on health.',
         'His "Book of Healing" was a philosophical and scientific encyclopedia covering logic, physics, mathematics, and metaphysics.'],
    form:['The Canon organized medicine into: general principles, simple drugs (materia medica), diseases by body part, systemic conditions, and compound remedies.',
          'He distinguished mediastinitis from pleurisy and described over 700 drugs with their properties and dosages.'],
    app:['The Canon was translated into Latin in the 12th century and remained a required text at European medical schools until the 1650s.',
         'His distinction between essence and existence influenced both Islamic and Christian scholastic philosophy.']},
   ['al_razI','al_khwarizmi','ibn_al_haytham','canon_of_medicine']),

  kb('canon_of_medicine','Canon of Medicine',['al-qanun fi al-tibb','avicenna canon'],
    'Ibn Sina\'s medical encyclopedia that systematized all known medical knowledge and remained authoritative for six centuries.',{
    def:['Written by Ibn Sina (Avicenna) around 1025 CE, the Canon (Al-Qanun fi al-Tibb) spans five books and over a million words.',
         'It synthesized Greek (Hippocrates, Galen), Persian, Indian, and Arabic medical knowledge into a unified system.'],
    int:['The Canon treated medicine as a rational science based on observation and logic, not superstition.',
         'It introduced concepts like clinical trials, quarantine, and evidence-based practice centuries before they appeared in Europe.'],
    ex:['Book I covers general principles: anatomy, physiology, pathology, diagnosis, and treatment.',
         'Book II describes 760 simple drugs; Book III covers diseases by organ; Book IV covers systemic diseases; Book V covers compound remedies.'],
    form:['The humoral theory organized health as balance of four humors (blood, phlegm, yellow bile, black bile) corresponding to four qualities (hot, cold, wet, dry).',
          'Pulse diagnosis classified pulses by rate, rhythm, amplitude, and regularity \u2014 a sophisticated diagnostic tool.'],
    app:['Translated to Latin by Gerard of Cremona in the 12th century, it became the standard medical textbook at Montpellier, Leuven, and other European universities.',
         'Its emphasis on systematic observation and classification influenced the development of modern clinical medicine.']},
   ['ibn_sina','al_razI','medicine']),

  kb('ibn_al_haytham','Ibn al-Haytham (Alhazen)',['alhazen','ibn al-haytham','hasan ibn al-haytham','ibnalhaytham','al-haytham','haytham'],
    'Arab scientist who founded optics as an experimental science and pioneered the scientific method.',{
    def:['Abu Ali al-Hasan ibn al-Hasan ibn al-Haytham (965\u20131040), known in the West as Alhazen, was an Arab polymath.',
         'His "Book of Optics" (Kitab al-Manazir) revolutionized understanding of light, vision, and scientific methodology.'],
    int:['He was the first to prove that vision occurs when light enters the eye, not when rays emanate from it (refuting Euclid and Ptolemy).',
         'He established that scientific theories must be proven through repeatable experiments \u2014 the birth of the experimental method.'],
    ex:['He used the camera obscura to prove that light travels in straight lines.',
         'He explained rainbows, atmospheric refraction, and twilight through careful observation and experimentation.'],
    form:['His method: observe a phenomenon, propose a hypothesis, design experiments to test it, analyze results mathematically, and draw conclusions.',
          'He studied spherical and parabolic mirrors, lens aberration, and magnification \u2014 laying groundwork for telescopes and microscopes.'],
    app:['His optics influenced Kepler, Descartes, Newton, and the entire European scientific revolution.',
         'His experimental method prefigured the modern scientific method by 600 years.']},
   ['optics','camera_obscura','scientific_method','al_razI']),

  kb('optics','Optics in the Golden Age',['ilm al-manazir','golden age optics'],
    'The science of light and vision as developed by Golden Age scholars, founded by Ibn al-Haytham.',{
    def:['"Ilm al-Manazir" (science of vision) was transformed from Greek speculation into an experimental science by Ibn al-Haytham.',
         'It studied light propagation, reflection, refraction, lenses, mirrors, and the anatomy of the eye.'],
    int:['Greek optics held that vision worked by rays shooting out of the eyes. Ibn al-Haytham proved the opposite: light enters the eye from objects.',
         'This reversal was as revolutionary as Copernicus placing the Sun instead of Earth at the center.'],
    ex:['Ibn al-Haytham correctly explained moonlight as reflected sunlight and analyzed the apparent enlargement of the moon at the horizon.',
         'Kamal al-Din al-Farisi later used Ibn al-Haytham\'s work to give the first correct explanation of the rainbow.'],
    form:['The law of refraction was studied empirically; Ibn Sahl (984) described what we now call Snell\'s law for lens design.',
          'The camera obscura demonstrated that light travels in straight lines and forms inverted images through small apertures.'],
    app:['Optical knowledge enabled eyeglasses, telescopes, microscopes, and cameras \u2014 tools that transformed science.',
         'Ibn al-Haytham\'s Latin works influenced Roger Bacon, Witelo, and Kepler directly.']},
   ['ibn_al_haytham','camera_obscura','ibn_sahl']),

  kb('translation_movement','Translation Movement',['graeco-arabic translation','translation movement abbasid','greek arabic translation','translation movement','arabic translation movement'],
    'Massive project to translate Greek, Persian, Indian, and Syriac scientific works into Arabic.',{
    def:['Beginning in the 8th century under the Abbasids, scholars translated the scientific heritage of antiquity into Arabic.',
         'The movement was state-sponsored, with caliphs paying translators their weight in gold.'],
    int:['It was the largest knowledge-transfer project in human history \u2014 preserving works that would have been lost and expanding them.',
         'Without this movement, much of Greek science and philosophy would have been lost to humanity.'],
    ex:['Hunayn ibn Ishaq alone translated nearly all of Galen\'s works, plus Aristotle, Plato, and Hippocrates.',
         'Indian astronomical tables (the Sindhind) and the decimal numeral system were translated and adopted.'],
    form:['Translation was systematic: teams of scholars fluent in Greek/Syriac and Arabic worked together for accuracy.',
          'Translators developed Arabic scientific terminology from scratch \u2014 words like "algebra," "algorithm," and "alkali" entered via this process.'],
    app:['The translated works became the foundation for original Islamic scholarship, which later flowed back to Europe via Toledo and Sicily.',
         'The translation movement established Arabic as the lingua franca of science for 500 years.']},
   ['house_of_wisdom','al_kindi','hunayn_ibn_ishaq']),

  kb('al_razI','Al-Razi (Rhazes)',['rhazes','al-razi','muhammad ibn zakariya'],
    'Persian physician and alchemist who distinguished smallpox from measles and pioneered clinical observation.',{
    def:['Abu Bakr Muhammad ibn Zakariya al-Razi (c. 854\u2013925), known in the West as Rhazes, was a Persian polymath.',
         'He was director of the Baghdad hospital and wrote over 200 works on medicine, alchemy, and philosophy.'],
    int:['Al-Razi was the first to distinguish smallpox from measles as distinct diseases with different symptoms and courses.',
         'He emphasized clinical observation over theoretical speculation \u2014 a proto-scientific approach to medicine.'],
    ex:['He chose the site for Baghdad\'s hospital by hanging pieces of meat in different districts and selecting where decomposition was slowest.',
         'His "Comprehensive Book on Medicine" (al-Hawi) was a 23-volume medical encyclopedia based on case studies.'],
    form:['He classified diseases by symptoms and progression, not by humoral theory alone.',
          'In alchemy, he classified substances into mineral, vegetable, and animal, and described distillation and crystallization techniques.'],
    app:['Al-Hawi was translated into Latin as "Continens" and became a foundational medical text in medieval Europe.',
         'His emphasis on observation and experimentation influenced later physicians including Ibn Sina.']},
   ['ibn_sina','canon_of_medicine','medicine','alchemy']),

  kb('astrolabe','Astrolabe',['astronomical astrolabe','islamic astrolabe'],
    'Sophisticated astronomical instrument for solving problems relating to time, position, and celestial motion.',{
    def:['A planar projection instrument consisting of a mater (body), rete (star map), plates (climate-specific projections), and alidade (sighting rule).',
         'Could determine time, latitude, prayer directions, and planetary positions from stellar observations.'],
    int:['The astrolabe was the smartphone of the medieval world \u2014 a portable analog computer for astronomy, navigation, and timekeeping.',
         'Islamic scholars perfected the astrolabe, adding universal plates and spherical projections.'],
    ex:['Al-Zarqali\'s saphea astrolabe worked at any latitude without changing plates.',
         'Nasir al-Din al-Tusi\'s astrolabe incorporated his mathematical innovations for more accurate calculations.'],
    form:['The stereographic projection from the south pole onto the equatorial plane preserved angles, making the astrolabe mathematically precise.',
          'The shadow square on the back enabled height and distance calculations using trigonometry.'],
    app:['Astrolabes enabled navigation across the Indian Ocean and later the Atlantic.',
         'They were essential for determining prayer times and the qibla direction across the Islamic world.']},
   ['astronomy','al_zarqali','nasir_al_din_tusi']),

  kb('astronomy','Astronomy in the Golden Age',['ilm al-falak','islamic astronomy'],
    'Highly advanced astronomical science developed in the Islamic world, combining Greek, Persian, and Indian traditions.',{
    def:['Islamic astronomers built observatories, compiled precise star catalogs, and refined planetary models.',
         'They corrected Ptolemy\'s Almagest, calculated the length of the solar year to remarkable accuracy, and named most visible stars.'],
    int:['Astronomy was both a practical science (for prayer times, qibla, calendar) and a theoretical pursuit (planetary models).',
         'The Maragha school\'s mathematical innovations directly influenced Copernicus.'],
    ex:['Al-Battani calculated the solar year as 365.24255 days (modern value: 365.24219).',
         'The Ulugh Beg Observatory in Samarkand produced a star catalog of 1,018 stars with unprecedented accuracy.'],
    form:['The Tusi couple \u2014 a mathematical device where a small circle rolls inside a larger one \u2014 resolved Ptolemaic inconsistencies.',
          'Equatorium instruments mechanically solved the equations of planetary motion.'],
    app:['Star names like Aldebaran, Altair, Betelgeuse, Rigel, and Vega all derive from Arabic.',
         'Astronomical tables (zij) were used for navigation and calendar calculation across three continents.']},
   ['astrolabe','al_battani','maragha_school','ulugh_beg']),

  kb('algebra_development','Development of Algebra',['history of algebra','algebra evolution'],
    'The evolution of algebra from Al-Khwarizmi\'s rhetorical algebra to symbolic notation.',{
    def:['Algebra evolved through three stages: rhetorical (words only), syncopated (abbreviations), and symbolic (modern notation).',
         'Islamic scholars carried algebra from geometric problem-solving to a general theory of equations.'],
    int:['Al-Khwarizmi\'s algebra was rhetorical \u2014 equations written entirely in words. "A square and ten roots equal thirty-nine."',
         'Omar Khayyam classified and solved cubic equations geometrically; al-Karaji began arithmetizing algebra.'],
    ex:['Thabit ibn Qurra gave a general proof for amicable numbers using algebraic reasoning.',
         'Al-Samawal\'s work on polynomial division anticipated modern algebra by centuries.'],
    form:['The six canonical forms of Al-Khwarizmi were gradually reduced as negative numbers gained acceptance.',
          'The fundamental theorem of algebra (every polynomial has a root) was conjectured but not proven until Gauss.'],
    app:['Algebra became the language of all quantitative science.',
         'The abstraction from specific numbers to general symbols enabled modern mathematics and physics.']},
   ['al_khwarizmi','omar_khayyam','algebra']),

  kb('maragha_school','Maragha School',['maragheh observatory','tusi couple'],
    'School of astronomers at the Maragha Observatory who developed alternatives to Ptolemaic astronomy.',{
    def:['Founded by Nasir al-Din al-Tusi in 1259 in northwestern Persia, the Maragha school produced revolutionary astronomical models.',
         'The observatory housed a library of 400,000 volumes and instruments including a 6-meter sextant.'],
    int:['The Tusi couple \u2014 two circles where one rolls inside the other \u2014 generated linear motion from circular motion.',
         'This resolved a key problem in Ptolemy\'s models and influenced Copernicus directly.'],
    ex:['Al-Tusi\'s planetary models eliminated the equant point that violated uniform circular motion.',
         'Ibn al-Shatir\'s models for the Moon and planets were mathematically identical to Copernicus\' later models.'],
    form:['The Maragha school\'s innovations: universal solutions replacing ad-hoc Ptolemaic devices, physical reality as criterion, mathematical consistency.',
          'Copernicus likely encountered these ideas through Byzantine Greek translations circulating in Italy.'],
    app:['The Maragha school bridged Islamic and European astronomy \u2014 their models directly influenced the Copernican revolution.',
         'The observatory model influenced later institutions like Ulugh Beg\'s Samarkand observatory and Tycho Brahe\'s Uraniborg.']},
   ['astronomy','nasir_al_din_tusi','ibn_al_shatir']),

  kb('paper_making','Paper Making',['paper islam','spread of paper'],
    'Introduction and spread of papermaking technology from China through the Islamic world to Europe.',{
    def:['Papermaking reached the Islamic world after the Battle of Talas (751), where Chinese prisoners revealed the technique.',
         'By 800, paper mills operated in Baghdad, Damascus, Cairo, Cordoba, and Fez.'],
    int:['Paper was cheaper and more durable than parchment, enabling mass production of books and democratizing knowledge.',
         'The paper revolution made the translation movement and the flourishing of libraries possible.'],
    ex:['Baghdad had over 100 paper mills by 900 CE.',
         'The library of Tripoli reportedly held 3 million volumes before its destruction in 1109.'],
    form:['Islamic papermakers improved Chinese techniques: linen and hemp fibers, starch sizing, watermarks.',
          'The codex form (bound pages) replaced scrolls, enabling random access to text.'],
    app:['Paper enabled the proliferation of books, libraries, and literacy across the Islamic world.',
         'Paper reached Europe via Islamic Spain in the 12th century, enabling the Renaissance and printing press.']},
   ['house_of_wisdom','translation_movement']),

  kb('ibn_rushd','Ibn Rushd (Averroes)',['averroes','ibn rushd','ibnrushd','ibn-rushd','averroes ibn rushd'],
    'Andalusian philosopher and jurist whose commentaries on Aristotle shaped medieval European thought.',{
    def:['Abu al-Walid Muhammad ibn Ahmad ibn Rushd (1126\u20131198), known as Averroes, was an Andalusian polymath.',
         'He wrote extensive commentaries on Aristotle that became standard texts in European universities.'],
    int:['Ibn Rushd argued that philosophy and religion were two paths to the same truth \u2014 reason and revelation cannot contradict.',
         'His "incompatibility of incompatibility" argued that apparent conflicts between philosophy and scripture arise from misinterpretation.'],
    ex:['His "Tahafut al-Tahafut" (Incoherence of the Incoherence) defended philosophy against Al-Ghazali\'s critiques.',
         'His medical work "Al-Kulliyat" (Colliget) was a comprehensive medical encyclopedia used in Europe.'],
    form:['He distinguished three levels of discourse: rhetorical (for masses), dialectical (for theologians), demonstrative (for philosophers).',
          'His concept of "unity of the intellect" influenced Latin Averroism and debates at the University of Paris.'],
    app:['"The Commentator" (as he was known in Latin) shaped Aquinas, Maimonides, and all of medieval scholasticism.',
         'Averroism became a major intellectual movement in 13th-century Europe.']},
   ['al_ghazali','ibn_sina','philosophy']),

  kb('al_ghazali','Al-Ghazali',['algazel','abu hamid al-ghazali','al ghazali','alghazali','ghazali','imam al-ghazali'],
    'Influential Islamic theologian, jurist, and mystic who critiqued excessive rationalism in philosophy.',{
    def:['Abu Hamid Muhammad al-Ghazali (1058\u20131111) was a Persian theologian and Sufi mystic.',
         'His "Incoherence of the Philosophers" critiqued Neoplatonic philosophy\'s claims to certain knowledge.'],
    int:['Al-Ghazali did not reject reason itself but argued that philosophical metaphysics overstepped its bounds.',
         'His spiritual crisis and turn to Sufism produced one of the most influential works of Islamic spirituality.'],
    ex:['He identified 20 points where philosophers contradicted Islamic doctrine, particularly on the eternity of the world and God\'s knowledge of particulars.',
         'His "Revival of the Religious Sciences" synthesized jurisprudence, theology, and mysticism.'],
    form:['His critique targeted the Neoplatonic emanation theory and the philosophers\' claim of necessary causal connections.',
          'He argued that causation is habitual, not necessary \u2014 anticipating Hume\'s critique of causation by 600 years.'],
    app:['His work prompted responses from Ibn Rushd and shaped the boundaries between philosophy and theology.',
         'His spiritual writings remain among the most influential in Islamic thought.']},
   ['ibn_rushd','ibn_sina','philosophy']),

  kb('medicine_golden_age','Medicine in the Golden Age',['tibb','islamic medicine'],
    'Medical science as practiced and advanced in the Islamic world, combining Greek theory with clinical observation.',{
    def:['Islamic medicine synthesized Hippocratic-Galenic theory with Persian, Indian, and original clinical observations.',
         'Hospitals (bimaristans) were established across the Islamic world as centers of treatment and teaching.'],
    int:['Medicine was professionalized: physicians required licenses, pharmacies were regulated, and hospitals had wards for different diseases.',
         'The concept of "first, do no harm" and evidence-based practice were central.'],
    ex:['Al-Razi distinguished smallpox from measles; Ibn al-Nafis described pulmonary circulation 300 years before Harvey.',
         'Al-Zahrawi\'s surgical encyclopedia described over 200 surgical instruments, many invented by him.'],
    form:['Medical education required studying anatomy, physiology, pathology, pharmacology, and clinical practice.',
          'Hospitals like Al-Mansuri in Cairo had separate wards, pharmacies, libraries, and lecture halls.'],
    app:['Islamic medical texts remained standard in Europe for centuries after the Renaissance.',
         'Modern medical ethics, licensing, and hospital organization owe much to Islamic models.']},
   ['ibn_sina','al_razI','canon_of_medicine','al_zahrawi']),

  kb('al_biruni','Al-Biruni',['biruni','abu rayhan'],
    'Persian scholar who made groundbreaking contributions to astronomy, geography, and comparative religion.',{
    def:['Abu Rayhan Muhammad ibn Ahmad al-Biruni (973\u20131048) was a Persian polymath.',
         'He calculated Earth\'s radius with remarkable accuracy and wrote extensively on India\'s sciences and culture.'],
    int:['Al-Biruni was arguably the first anthropologist \u2014 he studied cultures objectively without imposing his own biases.',
         'His scientific method emphasized repeated observation, measurement, and cross-verification.'],
    ex:['He calculated Earth\'s radius as 6,339 km (modern: 6,371 km) using a mountain height and horizon dip angle.',
         'His "India" (Tarikh al-Hind) described Indian mathematics, astronomy, religion, and customs with remarkable objectivity.'],
    form:['He discussed whether the Earth rotates on its axis, noting that observable phenomena would be the same either way.',
          'He compiled astronomical tables and described the astrolabe with mathematical rigor.'],
    app:['His geographical works influenced later cartographers and explorers.',
         'His comparative approach to religion anticipated modern religious studies by a millennium.']},
   ['astronomy','al_khwarizmi']),

  kb('al_zahrawi','Al-Zahrawi (Abulcasis)',['abulcasis','al-zahrawi'],
    'Andalusian surgeon whose medical encyclopedia was the standard surgical text in Europe for 500 years.',{
    def:['Abu al-Qasim Khalaf ibn al-Abbas al-Zahrawi (936\u20131013), known as Abulcasis, was an Andalusian physician.',
         'His "Al-Tasrif" was a 30-volume medical encyclopedia; volume 30 on surgery was especially influential.'],
    int:['Al-Zahrawi elevated surgery from a manual craft to a medical science based on anatomy and observation.',
         'He invented or described dozens of surgical instruments still recognizable today.'],
    ex:['He pioneered cauterization, ligatures for controlling bleeding, and surgical removal of bladder stones.',
         'He described procedures for cataract surgery, tooth extraction, amputation, and setting broken bones.'],
    form:['The Al-Tasrif covered: medicine, surgery, orthopedics, ophthalmology, pharmacology, nutrition, and childbirth.',
          'His illustrations of surgical instruments became the standard reference for European surgeons.'],
    app:['Translated to Latin by Gerard of Cremona, the Al-Tasrif was used at Montpellier and other European medical schools until the 16th century.',
         'Many modern surgical instruments trace their design to al-Zahrawi\'s originals.']},
   ['medicine_golden_age','al_razI','ibn_sina']),

  kb('ibn_al_nafis','Ibn al-Nafis',['ibn al-nafis','ala al-din'],
    'Arab physician who discovered pulmonary circulation 300 years before William Harvey.',{
    def:['Ala al-Din Abu al-Hasan Ibn al-Nafis (1213\u20131288) was an Arab physician and anatomist.',
         'He correctly described how blood flows from the right ventricle through the lungs to the left ventricle.'],
    int:['He refuted Galen\'s theory that blood passes through invisible pores in the heart septum.',
         'His discovery was not widely known in Europe until the 20th century, when his manuscript was rediscovered.'],
    ex:['"The blood is purified in the lungs, then passes from the right chamber to the left through the pulmonary artery and veins."',
         'He also described coronary circulation and capillary function.'],
    form:['His commentary on Ibn Sina\'s Canon contained his circulatory insights, which went unnoticed for centuries.',
          'He correctly stated that the heart is nourished by coronary arteries, not by blood in its chambers.'],
    app:['His work anticipated Harvey\'s complete description of systemic circulation.',
         'Modern historians recognize him as the true discoverer of pulmonary circulation.']},
   ['medicine_golden_age','ibn_sina','canon_of_medicine']),

  kb('philosophy_golden_age','Philosophy in the Golden Age',['falsafa','islamic philosophy'],
    'The philosophical tradition that synthesized Greek philosophy with Islamic theology.',{
    def:['Falsafa (philosophy) was the rationalist tradition in Islamic thought, drawing on Aristotle, Plato, and Neoplatonism.',
         'Key figures include Al-Kindi, Al-Farabi, Ibn Sina, and Ibn Rushd.'],
    int:['Philosophers argued that reason and revelation are compatible paths to truth.',
         'They developed original metaphysics, epistemology, ethics, and political philosophy.'],
    ex:['Al-Farabi\'s "Virtuous City" described an ideal state governed by philosopher-prophets.',
         'Ibn Sina\'s distinction between essence and existence influenced both Islamic and Christian scholasticism.'],
    form:['The translation of Aristotle\'s works sparked original commentary and critique, not mere repetition.',
          'The debate between rationalists (falasifa) and traditionalists (like Al-Ghazali) defined Islamic intellectual history.'],
    app:['Islamic philosophy transmitted Greek thought to medieval Europe and shaped scholasticism.',
         'Questions about faith and reason, universals, and the nature of God remain central to philosophy.']},
   ['al_kindi','ibn_sina','ibn_rushd','al_ghazali']),

  kb('al_farabi','Al-Farabi',['al-farabi','farabi','second teacher','alpharabius'],
    'Central Asian philosopher and political theorist who systematized Islamic philosophy and wrote on the ideal state.',{
    def:['Abu Nasr Muhammad al-Farabi (c. 872\u2013950), known as the "Second Teacher" (after Aristotle), was a Persian or Central Asian philosopher.',
         'He wrote influential commentaries on Aristotle and Plato and developed an original political philosophy in "The Virtuous City" (Al-Madina al-Fadila).'],
    int:['Al-Farabi was the first Islamic philosopher to fully articulate a systematic philosophy encompassing logic, epistemology, metaphysics, and political theory.',
         'He envisioned an ideal society led by a philosopher-prophet, anticipating Plato\'s philosopher-king but within an Islamic framework.'],
    ex:['His "Book of Letters" analyzed the origin of language and philosophy.',
         'He classified the sciences into a hierarchy: linguistics, logic, mathematics, physics, metaphysics, and politics.'],
    form:['The "Second Teacher" title reflects his role in explaining and expanding Aristotle\'s Organon, adding new commentaries on the Prior and Posterior Analytics.',
          'Al-Farabi\'s political philosophy synthesized Plato\'s Republic with Islamic concepts of prophecy and revelation.'],
    app:['His classification of knowledge influenced the medieval European university curriculum.',
         'His ideas on the virtuous society influenced later political thinkers like Ibn Sina and Ibn Rushd.']},
   ['philosophy_golden_age','ibn_sina','ibn_rushd','al_kindi']),

  kb('omar_khayyam','Omar Khayyam',['omar khayyam','khayyam','persian mathematician','rubaiyat'],
    'Persian polymath who solved cubic equations geometrically and is also renowned for his poetry.',{
    def:['Ghiyath al-Din Abu\'l-Fath Umar ibn Ibrahim al-Nishaburi al-Khayyami (1048\u20131131), known as Omar Khayyam, was a Persian mathematician, astronomer, and poet.',
         'He classified cubic equations and solved them by intersecting conic sections, and helped reform the Persian calendar.'],
    int:['Khayyam bridged mathematics and poetry with equal mastery \u2014 his "Rubaiyat" (quatrains) are among the most famous poems in world literature.',
         'The Jalali calendar he helped devise is more accurate than the Gregorian calendar, drifting only one day every 3770 years.'],
    ex:['He solved 13 classes of cubic equations using intersections of circles, parabolas, and hyperbolas.',
         'His quatrains, popularized in the West by Edward FitzGerald\'s 1859 translation, explore themes of fate, mortality, and carpe diem.'],
    form:['In his "Treatise on Demonstration of Problems of Algebra," he gave geometric solutions for all cubic equations, not just those with positive roots.',
          'He proved that a cubic equation can have at most three real roots and discussed the relationship between equations and conic sections.'],
    app:['His geometric approach to cubics influenced the development of algebraic geometry.',
         'His poetry has been translated into every major language and remains a cultural touchstone in Iran and the West.']},
   ['algebra_development','al_khwarizmi','al_biruni']),

  kb('al_zarqali','Al-Zarqali',['al-zarqali','arzaquiel','toledo astronomer','saphea'],
    'Andalusian astronomer and instrument maker who invented the universal astrolabe and improved astronomical tables.',{
    def:['Abu Ishaq Ibrahim ibn Yahya al-Zarqali (also known as Zarqali or Arzaquiel, 1028\u20131087) was a leading Andalusian astronomer and instrument maker based in Toledo.',
         'He built and designed precision instruments, most notably the "saphea" (universal astrolabe plate) that worked at any latitude.'],
    int:['Al-Zarqali was the first to prove that the motion of the solar apogee relative to the fixed stars is not constant \u2014 a challenge to Ptolemaic astronomy.',
         'His instruments were so precise they were used for centuries across Europe and the Islamic world.'],
    ex:['His Toledan Tables (based on extensive observations) were the most accurate astronomical tables in Europe for over 200 years.',
         'The saphea (safiha) astrolabe could be used at any latitude without changing the plate, a major innovation over earlier instruments.'],
    form:['He determined the rate of the solar apogee\'s motion as 12.04 seconds of arc per year (modern: 11.8\'\').',
          'His data on the obliquity of the ecliptic gave 23\\u00b033\' (compared to Ptolemy\'s 23\\u00b051\').'],
    app:['The Toledan Tables were translated into Latin and used by Copernicus and other European astronomers.',
         'His astrolabe designs influenced instrument makers across Europe and the Islamic world for centuries.']},
   ['astrolabe','astronomy','al_farghani']),

  kb('nasir_al_din_tusi','Nasir al-Din al-Tusi',['tusi','nasir al-din','khajeh nasir','maragha astronomer'],
    'Persian polymath who founded the Maragha Observatory and developed the Tusi couple, influencing Copernican astronomy.',{
    def:['Muhammad ibn Muhammad ibn al-Hasan al-Tusi (1201\u20131274), known as Nasir al-Din al-Tusi, was a Persian polymath who wrote on astronomy, mathematics, philosophy, and theology.',
         'He founded the Maragha Observatory in 1259, the most advanced astronomical institution of its time, and developed the "Tusi couple" \u2014 a mathematical device that converts circular into linear motion.'],
    int:['The Tusi couple elegantly resolved a fundamental problem in Ptolemaic astronomy: how to explain planetary motion with uniform circular motion alone.',
         'Al-Tusi was one of the first to treat trigonometry as a separate mathematical discipline, independent of astronomy.'],
    ex:['He compiled the Ilkhanic Tables (Zij-i Ilkhani), the most accurate astronomical tables of the medieval period.',
         'His Tusi couple \u2014 a small circle rotating inside a larger circle of twice its radius \u2014 produces straight-line motion from two circular motions.'],
    form:['The Tusi couple: a circle of radius $r$ rolls internally inside a circle of radius $2r$; a point on the smaller circle traces a diameter of the larger.',
          'His "Treatise on the Complete Quadrilateral" (Kitab al-Shakl al-Qatta) systematized plane and spherical trigonometry.'],
    app:['The Tusi couple was used by Copernicus in his planetary models, suggesting direct transmission of Maragha ideas to Renaissance Europe.',
         'His work on trigonometry established it as a foundation for modern mathematics and navigation.']},
   ['maragha_school','astronomy','ibn_al_shatir','ulugh_beg']),

  kb('ibn_al_shatir','Ibn al-Shatir',['ibn al-shatir','ala al-din ibn al-shatir','damascene astronomer'],
    'Damascene astronomer whose lunar and planetary models were mathematically identical to Copernicus\' later formulations.',{
    def:['Ala al-Din Abu\'l-Hasan Ali ibn Ibrahim ibn al-Shatir (1304\u20131375) was an Arab astronomer and muwaqqit (timekeeper) at the Umayyad Mosque in Damascus.',
         'He produced new planetary models that eliminated the equant and epicycle anomalies in Ptolemaic astronomy, using only combinations of uniformly rotating circles.'],
    int:['Ibn al-Shatir\'s models for the Moon and Mercury are mathematically identical to those later used by Copernicus, raising profound questions about transmission of ideas.',
         'He was a practicing timekeeper who needed accurate astronomical tables for determining prayer times.'],
    ex:['His lunar model correctly predicted the Moon\'s distance variation, which Ptolemy\'s model could not.',
         'His planetary models provided more accurate predictions of planetary positions than Ptolemy\'s Almagest.'],
    form:['He used a system of epicycles and deferents that exactly matches Copernicus\' later arrangement for the Moon: two epicycles on a deferent centered on Earth.',
          'For Mercury, his model is virtually identical to Copernicus\' model for that planet.'],
    app:['His work provides the strongest evidence that Copernicus\' heliocentric models had precursors in Islamic astronomy.',
         'Shows the continuity of astronomical science across cultures and centuries.']},
   ['maragha_school','astronomy','nasir_al_din_tusi','al_battani']),

  kb('ulugh_beg','Ulugh Beg',['ulugh beg','samarkand observatory','ulugh beg observatory'],
    'Timurid sultan, mathematician, and astronomer who built the world\'s largest observatory and compiled a stellar catalog of unprecedented accuracy.',{
    def:['Muhammad Taraghai ibn Shahrukh ibn Timur (1394\u20131449), known as Ulugh Beg, was a Timurid sultan and astronomer who ruled Samarkand.',
         'He built the Samarkand Observatory (1420s) with a giant 40-meter sextant (the Fakhri sextant) and produced the Zij-i Sultani star catalog of 1,018 stars.'],
    int:['Ulugh Beg was a ruler who prioritized science over conquest \u2014 his observatory was the most advanced in the world until Tycho Brahe\'s Uraniborg.',
         'His star catalog was the first original catalog since Ptolemy\'s and remained the most accurate for over 200 years.'],
    ex:['He calculated the length of the sidereal year as 365.2570380 days (modern: 365.2563630), accurate to within one minute.',
         'His catalog of 1,018 stars gave positions more accurate than Copernicus\' later catalog.'],
    form:['The Fakhri sextant had a radius of 40 meters, allowing angular measurements to a precision of a few arcseconds.',
          'His astronomical tables included trigonometric functions, planetary positions, and precession rates.'],
    app:['The Ulugh Beg catalog was used by European astronomers including John Flamsteed and Edmond Halley.',
         'His observatory established a global standard for institutional astronomical research.']},
   ['astronomy','maragha_school','nasir_al_din_tusi','al_battani']),

  kb('al_battani','Al-Battani',['al-battani','albategnius','battani','harran astronomer'],
    'Arab astronomer and mathematician who made remarkably accurate astronomical observations and improved Ptolemy\'s star catalog.',{
    def:['Abu Abd Allah Muhammad ibn Jabir ibn Sinan al-Battani (c. 858\u2013929), known in the West as Albategnius, was an Arab astronomer and mathematician from Harran.',
         'He made highly accurate observations over 41 years, determining the solar year length, precession of the equinoxes, and inclination of the ecliptic.'],
    int:['Al-Battani\'s observations were so precise that they were used by Copernicus, Kepler, and Tycho Brahe centuries later.',
         'He corrected many of Ptolemy\'s errors and provided the empirical basis for later European astronomy.'],
    ex:['He calculated the solar year as 365.24255 days (modern: 365.24219), accurate to within 0.00036 days (about 31 seconds).',
         'He corrected the obliquity of the ecliptic from Ptolemy\'s 23\\u00b051\' to 23\\u00b035\' (modern: 23\\u00b026\').'],
    form:['His major work, "Kitab al-Zij," contained 57 chapters covering astronomy, trigonometry, and astronomical instruments.',
          'He introduced the use of sines and tangents in astronomical calculations, moving beyond Ptolemy\'s chord-based methods.'],
    app:['His observational data became a cornerstone of European astronomy for 700 years.',
         'Many European astronomers (Copernicus, Kepler, Galileo) relied on his tables and observations.']},
   ['astronomy','astrolabe','al_farghani','ulugh_beg']),

  kb('hunayn_ibn_ishaq','Hunayn ibn Ishaq',['hunayn ibn ishaq','johannitius','abu zaid'],
    'Nestorian Christian translator, physician, and scholar who led the translation of Greek medical texts into Arabic.',{
    def:['Abu Zayd Hunayn ibn Ishaq al-Ibadi (809\u2013873) was a Nestorian Christian scholar who became the most prolific translator of Greek medical and philosophical works into Arabic.',
         'He was appointed director of the House of Wisdom\'s translation bureau under Caliph al-Mutawakkil and translated nearly all of Galen\'s works.'],
    int:['Hunayn\'s translation method was rigorous: he compared multiple Greek manuscripts to produce the most accurate Arabic version.',
         'He was paid by the weight of his translations in gold, reflecting the immense value placed on his work.'],
    ex:['He translated over 100 works of Galen, 17 of Aristotle, and numerous works of Hippocrates, Plato, and Dioscorides.',
         'His "Book of the Ten Treatises on the Eye" was the first systematic textbook of ophthalmology.'],
    form:['His method: first establish the best Greek text by comparing manuscripts, then translate into Syriac, and finally into elegant Arabic with a team of editors.',
          'He developed Arabic medical terminology that became the standard across the Islamic world.'],
    app:['Without Hunayn\'s translations, much of Galenic medicine and Greek philosophy would have been lost to posterity.',
         'His translations later reached Europe via the School of Toledo, becoming the basis for medieval European medicine.']},
   ['translation_movement','house_of_wisdom','al_kindi','medicine_golden_age']),

  kb('al_idrisi','Al-Idrisi',['al-idrisi','idrisi','dreses','nubian geographer','roger\'s book'],
    'Arab geographer and cartographer who created the most accurate world map and geographical encyclopedia of the pre-modern era.',{
    def:['Abu Abd Allah Muhammad al-Idrisi al-Qurtubi al-Hasani al-Sabti (1100\u20131165) was an Arab geographer and cartographer who worked at the court of King Roger II of Sicily.',
         'He created the "Tabula Rogeriana" (Nuzhat al-Mushtaq), a world atlas with 70 regional maps and a silver celestial globe.'],
    int:['Al-Idrisi gathered geographical data by interviewing travelers and merchants from across the known world, synthesizing Islamic, Greek, and European knowledge.',
         'His maps were the most accurate of their time and remained authoritative in Europe for three centuries.'],
    ex:['The Tabula Rogeriana was accompanied by a silver celestial globe weighing 400 kg, showing the known world in unprecedented detail.',
         'His atlas accurately showed the sources of the Nile, the Baltic Sea, and the Volga River.'],
    form:['The world was divided into 7 climatic zones (following Ptolemy), each subdivided into 10 sections, with detailed regional maps and a global overview.',
          'His work synthesized data from Greek (Ptolemy), Islamic (Ibn Hawqal), and European sources with original travel reports.'],
    app:['Al-Idrisi\'s maps influenced European cartography for 300 years and were used by explorers including Columbus.',
         'His work remains a valuable historical record of 12th-century geographical knowledge.']},
   ['astronomy','paper_making','house_of_wisdom']),

  kb('ibn_khaldun','Ibn Khaldun',['ibn khaldun','khaldun','muqaddimah','father of historiography'],
    'Arab historian, philosopher, and social scientist whose Muqaddimah laid foundations for modern historiography and sociology.',{
    def:['Abd al-Rahman ibn Muhammad ibn Khaldun (1332\u20131406) was an Arab historian, philosopher, economist, and social scientist from Tunis.',
         'His masterpiece, the "Muqaddimah" (Prolegomenon), is the introduction to his universal history and is considered the first work of scientific historiography and sociology.'],
    int:['Ibn Khaldun developed a theory of history based on social cohesion (asabiyyah), analyzing the rise and fall of civilizations with a systematic methodology.',
         'He is often called the father of modern historiography, sociology, and economics \u2014 anticipating concepts like the labor theory of value and supply-and-demand.'],
    ex:['He analyzed how nomadic Bedouin tribes with strong asabiyyah conquer settled civilizations but gradually lose their cohesion, leading to decline.',
         'His cyclical theory of history: a dynasty lasts about 3-4 generations (roughly 120 years) before decay sets in.'],
    form:['The Muqaddimah has six parts: human civilization, Bedouin society, dynasties and rulership, sedentary civilization, crafts and livelihoods, and the sciences.',
          'He introduced the concept of asabiyyah (group solidarity) as the driving force of historical change.'],
    app:['His ideas influenced modern historians like Toynbee and sociologists like Durkheim and Weber.',
         'His interdisciplinary methodology anticipates modern social science by 500 years.']},
   ['philosophy_golden_age','al_biruni','al_idrisi']),

  kb('al_jazari','Al-Jazari',['al-jazari','jazzari','elephant clock','automata engineer','islamic engineer'],
    'Greatest mechanical engineer of the medieval Islamic world, known for his automata and programmable machines.',{
    def:['Badi\' al-Zaman Abu\'l-Izz ibn Isma\'il al-Jazari (1136\u20131206) was a Muslim polymath, mechanical engineer, and artisan from the Jazira region (modern-day Upper Mesopotamia).',
         'His "Book of Knowledge of Ingenious Mechanical Devices" described 100 mechanical devices with detailed instructions and diagrams.'],
    int:['Al-Jazari was the da Vinci of the Islamic world \u2014 centuries before the European Renaissance, he designed programmable robots, crankshafts, and water pumps.',
         'His book was designed as a practical manual for craftsmen, unlike earlier theoretical works.'],
    ex:['The elephant clock combined an Indian water clock, Egyptian phoenix automaton, Chinese dragons, and Arabic/mechanical elements in a stunning multicultural timepiece.',
         'He designed a hand-washing automaton with a programmable sequence (flush, soap, rinse) \u2014 the earliest known programmable humanoid robot.'],
    form:['He invented the crankshaft and the connecting rod, crucial components of the internal combustion engine and modern machinery.',
          'His cam-based automata used pegs on a rotating drum to trigger mechanical actions at specific times, a form of mechanical programming.'],
    app:['His crank-connecting rod mechanism is fundamental to modern machinery \u2014 engines, pumps, and industrial automation.',
         'His automata influenced European clockmaking and mechanical engineering via translations of his work.']},
   ['paper_making','ibn_sina','house_of_wisdom']),

  kb('banu_musa','Banu Musa Brothers',['banu musa','muhammad ibn musa','ahmad ibn musa','hasan ibn musa','book of ingenious devices'],
    'Three Persian brothers who produced the "Book of Ingenious Devices," a major work on mechanical engineering and automata.',{
    def:['Muhammad, Ahmad, and al-Hasan ibn Musa ibn Shakir (9th century) were three Persian brothers who studied at the House of Wisdom in Baghdad.',
         'Their "Book of Ingenious Devices" (Kitab al-Hiyal) described 100 mechanical devices including trick vessels, fountains, and automata.'],
    int:['The Banu Musa were among the first to apply Greek theoretical mechanics to practical engineering problems.',
         'Their automatic fountain with intermittent flow used a siphonic principle that was a precursor to modern feedback control.'],
    ex:['They designed the first conical valve (the "banu musa valve"), a self-regulating mechanism that controlled fluid flow.',
         'Their "gas mask" device was a mechanical apparatus that supplied fresh air to workers in contaminated environments.'],
    form:['Their work included sophisticated float-valve control systems, differential pressure sensors, and self-trimming lamps.',
          'The Book of Ingenious Devices is distinct from al-Jazari\'s later work in its focus on Greek-inspired theoretical mechanics over practical craft.'],
    app:['Their self-regulating mechanisms and feedback controls anticipated modern automation and control theory.',
         'Their engineering methods influenced both Islamic and European technological development.']},
   ['house_of_wisdom','al_jazari','translation_movement']),

  kb('thabit_ibn_qurra','Thabit ibn Qurra',['thabit ibn qurra','thebit','thabit','harran mathematician'],
    'Sabian mathematician, physician, and translator who made fundamental contributions to number theory and geometry.',{
    def:['Abu\'l-Hasan Thabit ibn Qurra ibn Marwan al-Sabi al-Harrani (826\u2013901) was a Sabian mathematician, physician, astronomer, and translator from Harran.',
         'He worked at the House of Wisdom and made pioneering contributions to number theory, geometry, and mechanics.'],
    int:['Thabit discovered the formula for amicable numbers \u2014 pairs of numbers where each equals the sum of the other\'s proper divisors.',
         'He also generalized the Pythagorean theorem and made important advances in integral calculus.'],
    ex:['His amicable pair (220, 284) was known to the Greeks, but Thabit\'s general formula allowed generation of many more.',
         'He generalized the Pythagorean theorem to arbitrary triangles in his "Book on the Measurement of Parabolic Solids."'],
    form:['Thabit\'s rule: if $p=3\\cdot2^{n-1}-1$, $q=3\\cdot2^n-1$, and $r=9\\cdot2^{2n-1}-1$ are all prime, then $2^n p q$ and $2^n r$ form an amicable pair.',
          'He used the method of exhaustion (attributed to Archimedes) to compute volumes of paraboloids.'],
    app:['His work on amicable numbers laid foundations for number theory developed later by Euler and Fermat.',
         'His translations of Archimedes, Euclid, and Ptolemy preserved these works and made them available to later Islamic and European scholars.']},
   ['translation_movement','house_of_wisdom','algebra','al_khwarizmi']),

  kb('al_karaji','Al-Karaji',['al-karaji','karaji','abu bakr','arithmetization of algebra'],
    'Persian mathematician who freed algebra from geometry by arithmetizing algebraic operations.',{
    def:['Abu Bakr Muhammad ibn al-Hasan al-Karaji (c. 953\u20131029) was a Persian mathematician who worked in Baghdad.',
         'His key works, "Al-Fakhri" and "Al-Badi\'," advanced algebra beyond Al-Khwarizmi by treating it as an arithmetic discipline.'],
    int:['Al-Karaji broke from the geometric tradition of algebra, showing that algebraic operations could be performed purely arithmetically.',
         'He discovered the binomial theorem and Pascal\'s triangle centuries before Pascal.'],
    ex:['He explicitly stated the binomial expansion $(a+b)^3 = a^3 + 3a^2b + 3ab^2 + b^3$ and extended it to higher powers.',
         'He developed algorithms for finding sums of powers of integers, $\\sum_{k=1}^n k$, $\\sum_{k=1}^n k^2$, and $\\sum_{k=1}^n k^3$.'],
    form:['His inductive reasoning for the binomial coefficients anticipated the modern combinatorial approach.',
          'He introduced the concept of "unknown quantity" ($shay\'$, "thing") that later became the $x$ in Renaissance algebra.'],
    app:['His arithmetic approach made algebra more systematic and computational, influencing later European algebraists.',
         'His work on sums of powers foreshadowed integral calculus.']},
   ['algebra','algebra_development','al_khwarizmi','al_samawal']),

  kb('al_samawal','Al-Samawal',['al-samawal','al-samaw\'al','samawal','polynomial algebra'],
    'Arab mathematician who developed techniques for polynomial arithmetic and division.',{
    def:['Al-Samawal ibn Yahya al-Maghribi (c. 1130\u20131180) was an Arab mathematician from Baghdad who wrote "Al-Bahir" (The Dazzling), a major work on algebra.',
         'He systematized operations on polynomials, including addition, subtraction, multiplication, and division of polynomials in multiple variables.'],
    int:['Al-Samawal extended al-Karaji\'s arithmetization of algebra by developing explicit algorithms for polynomial division.',
         'He treated polynomials as formal expressions, an important step toward symbolic algebra.'],
    ex:['He performed polynomial long division, a technique later rediscovered in Renaissance Europe.',
         'He correctly handled the division of polynomials with multiple variables and negative exponents.'],
    form:['He organized polynomial arithmetic using tables and algorithms that anticipated modern polynomial algebra.',
          'Al-Samawal\'s "Al-Bahir" presented the first known formulation of the binomial theorem for $(a+b)^n$ for arbitrary $n$.'],
    app:['His polynomial algorithms were foundational for the development of symbolic computation.',
         'His work influenced both Islamic and later European algebra.']},
   ['algebra','algebra_development','al_karaji','al_khwarizmi']),

  kb('ibn_sahl','Ibn Sahl',['ibn sahl','alawi','lens law','refraction pioneer'],
    'Persian mathematician and optician who discovered the law of refraction (Snell\'s law) 600 years before Snell.',{
    def:['Abu Sa\'d al-Ala\' ibn Sahl (c. 940\u20131000) was a Persian mathematician and optician who worked at the Abbasid court in Baghdad.',
         'In his "Treatise on Burning Instruments," he described the law of refraction now known as Snell\'s law: $n_1 \\sin \\theta_1 = n_2 \\sin \\theta_2$.'],
    int:['Ibn Sahl\'s discovery of the correct law of refraction was virtually unknown until the 20th century, when his manuscript was rediscovered in Tehran.',
         'He used his law to design "anaclastic" lenses that focus light without spherical aberration.'],
    ex:['He described the relationship between the angle of incidence and refraction for light passing from air into glass and water.',
         'His design of perfect focusing lenses (anaclastic lenses) required understanding the exact refraction law.'],
    form:['His derivation used the concept of the ratio of distances along the interface, equivalent to the ratio of sines of the angles.',
          'He expressed the law as: the ratio of the sine of incidence to the sine of refraction is constant for a given pair of media.'],
    app:['Ibn Sahl\'s work underlies all modern lens design, fiber optics, and optical engineering.',
         'His discovery predates Descartes and Snell by six centuries, yet was lost to history and rediscovered only in the 1990s.']},
   ['optics','ibn_al_haytham','al_kindi']),

  kb('al_farghani','Al-Farghani',['al-farghani','alfraganus','farghani','astronomer of the nile'],
    'Central Asian astronomer whose summary of Ptolemaic astronomy became a standard textbook in Europe and the Islamic world.',{
    def:['Abu\'l-Abbas Ahmad ibn Muhammad ibn Kathir al-Farghani (c. 800\u2013870), known in the West as Alfraganus, was a Persian astronomer from Farghana (modern Uzbekistan).',
         'His "Elements of Astronomy" (Kitab fi al-Harakat al-Samawiyah) was a concise summary of Ptolemaic astronomy that became a standard reference.'],
    int:['Al-Farghani\'s book was so clear and well-organized that it served as the primary astronomical textbook for centuries in both the Islamic world and Europe.',
         'He accurately calculated the Earth\'s diameter and the distances to celestial bodies using Ptolemaic methods.'],
    ex:['He calculated Earth\'s diameter as 6,500 miles (approximate), the circumference as 20,400 miles (remarkably close to modern values).',
         'He described the six planets known at the time, their distances from Earth, and their periods of revolution.'],
    form:['His "Elements of Astronomy" covered: celestial spheres, Earth\'s shape and size, planetary motions, solar and lunar cycles, and astronomical instruments.',
          'The work contained 30 chapters systematically organized for teaching.'],
    app:['Translated into Latin by Gerard of Cremona and by John of Seville, it was used by Dante, Columbus, and European astronomers for 500 years.',
         'Columbus used al-Farghani\'s calculations of Earth\'s size (though misinterpreting the Arabic miles) to support his westward voyage.']},
   ['astronomy','al_battani','al_zarqali','astrolabe']),

  kb('qusta_ibn_luqa','Qusta ibn Luqa',['qusta ibn luqa','costa ben luca','baalbek physician','translator physician'],
    'Melkite Christian translator, physician, and philosopher who bridged Greek and Arabic medicine and science.',{
    def:['Qusta ibn Luqa al-Ba\'albaki (820\u2013912) was a Melkite Christian physician, philosopher, astronomer, and translator from Baalbek (modern Lebanon).',
         'He translated numerous Greek works into Arabic, including the "Mechanics" of Hero of Alexandria and works by Aristotle, Galen, and Diophantus.'],
    int:['Qusta was one of the few translators who wrote extensively on his own intellectual contributions, not just translations.',
         'He wrote important original treatises on medicine, optics, and the relationship between body and soul.'],
    ex:['His treatise "On the Difference Between the Spirit and the Soul" was the first systematic psychological work in Arabic.',
         'He wrote on medical topics including epidemics, sexual health, and the therapeutic use of music.'],
    form:['He translated the pseudo-Aristotelian "Mechanics" (Mechanica Problemata), which influenced Islamic mechanical engineering.',
          'His original works were widely cited by later Islamic physicians and philosophers.'],
    app:['His translations preserved important Greek scientific works that might otherwise have been lost.',
         'His philosophical writings influenced the development of Islamic psychology and medicine.']},
   ['translation_movement','house_of_wisdom','hunayn_ibn_ishaq','medicine_golden_age']),

  kb('al_majriti','Al-Majriti',['al-majriti','majriti','abu muslim','andalusian astronomer','madrid astronomer'],
    'Andalusian mathematician, astronomer, and alchemist who established science in Islamic Spain.',{
    def:['Abu Muslim Muhammad ibn Ahmad al-Majriti (c. 950\u20131007) was an Andalusian mathematician, astronomer, and alchemist from Madrid (Majrit).',
         'He founded a school of mathematics and astronomy in Cordoba and edited and corrected the astronomical tables of al-Khwarizmi.'],
    int:['Al-Majriti introduced the science of al-Khwarizmi and the astrolabe to Islamic Spain, establishing a scientific tradition in the Maghreb.',
         'He was the first great Andalusian scientist, training a generation of scholars who would carry science in Spain to new heights.'],
    ex:['He corrected and adapted the astronomical tables of al-Khwarizmi to the meridian of Cordoba, making them usable in Spain.',
         'He wrote about practical applications of arithmetic for commerce, surveying, and trade.'],
    form:['His "Treatise on the Astrolabe" introduced the use of the universal astrolabe to Andalusian astronomers.',
          'As an alchemist, he wrote on the preparation of substances and the properties of metals.'],
    app:['His students spread mathematical and astronomical knowledge across North Africa and Europe.',
         'He established the bridge between Eastern Islamic and Andalusian science.']},
   ['astronomy','astrolabe','al_zarqali','al_farghani']),

  kb('fatima_al_fihri','Fatima al-Fihri',['fatima al-fihri','fatima al-fihriya','umm al-banin','founder of university','qarawiyyin founder'],
    'Arab woman who founded the University of al-Qarawiyyin, the oldest existing degree-granting university in the world.',{
    def:['Fatima bint Muhammad al-Fihri (c. 800\u2013880) was an Arab woman from Kairouan (Tunisia) who migrated to Fez, Morocco, and founded the al-Qarawiyyin Mosque and Madrasa in 859 CE.',
         'The associated institution evolved into the University of al-Qarawiyyin, recognized by UNESCO and the Guinness World Records as the oldest existing, continually operating educational institution awarding degrees.'],
    int:['Fatima used her inheritance from her father to build a mosque and school that would serve her community and become a beacon of learning for centuries.',
         'Her story is a remarkable example of female patronage of education in the 9th century.'],
    ex:['Al-Qarawiyyin attracted scholars from across the Islamic world, including Ibn Rushd (Averroes), Ibn al-Arabi, and the Jewish philosopher Maimonides.',
         'The library of al-Qarawiyyin holds some of the oldest manuscripts in existence, including a 9th-century Quran.'],
    form:['The institution began as a mosque-madrasa (school) teaching Quran, law, and grammar, and gradually expanded to include mathematics, astronomy, and medicine.',
          'It was among the first institutions to award formal degrees (ijazas) upon completion of studies.'],
    app:['Al-Qarawiyyin educated scholars who shaped Islamic and European intellectual history for over a millennium.',
         'It demonstrates the central role of educational institutions in the Islamic Golden Age.']},
   ['house_of_wisdom','paper_making','translation_movement']),

  kb('mariam_al_astrulabi','Mariam al-Astrulabi',['mariam al-astrulabi','al-astrulabiyya','female astrolabe maker'],
    '10th-century Syrian female astronomer and astrolabe maker, one of the few known women scientists of the Golden Age.',{
    def:['Mariam al-Astrulabiyya (c. 10th century CE) was a Syrian female astronomer and astrolabe maker from Aleppo.',
         'She excelled in the craft of astrolabe construction and was appointed by the Hamdanid ruler Sayf al-Dawla as the official court astrolabe maker.'],
    int:['Mariam\'s surviving reputation confirms that women participated in the scientific enterprise of the Golden Age, even in instrument-making \u2014 a highly skilled technical field.',
         'Her name "al-Astrulabiyya" means "the astrolabe maker," suggesting her profession was her defining identity.'],
    ex:['She crafted precision astrolabes for the court of Sayf al-Dawla in Aleppo, a major center of learning.',
         'Her instruments were used for navigation, timekeeping, and determining prayer times.'],
    form:['Astrolabe construction required mastery of stereographic projection, metalworking, engraving, and astronomical calculation.',
          'Each astrolabe had to be calibrated for a specific latitude and engraved with the correct star positions.'],
    app:['Her work exemplifies the contributions of women to the sciences in the medieval Islamic world.',
         'She serves as an important historical figure inspiring women in STEM today.']},
   ['astrolabe','astronomy','al_zarqali']),

  kb('lubana','Lubana of Cordoba',['lubana','lubna of cordoba','cordoban mathematician','andalusian scholar'],
    'Andalusian female mathematician and librarian who served at the Library of Cordoba.',{
    def:['Lubana (or Lubna) of Cordoba (10th century CE) was an Andalusian mathematician and librarian in the court of Caliph al-Hakam II in Cordoba.',
         'She was renowned for her knowledge of mathematics, poetry, and calligraphy, and served as the librarian of the Royal Library of Cordoba.'],
    int:['Lubana was one of the most educated women in al-Andalus, demonstrating that elite women could attain high levels of learning and professional status.',
         'The Library of Cordoba she helped manage reportedly held 400,000 to 600,000 volumes.'],
    ex:['She was described by historians as "the pride of her sex" and was skilled in solving complex geometrical and algebraic problems.',
         'She transcribed manuscripts and taught mathematics and poetry to noblewomen.'],
    form:['The Library of Cordoba under Caliph al-Hakam II was the largest library in the Western world, with a staff of librarians, translators, and copyists.',
          'Lubana was a leading figure in this intellectual institution, managing the largest book collection of its time in Europe.'],
    app:['Lubana represents the high point of female scholarship in medieval al-Andalus.',
         'Her work preserving and transmitting knowledge contributed to the foundations of the European Renaissance.']},
   ['paper_making','house_of_wisdom','al_majriti','al_zarqali']),

  kb('abbas_ibn_firnas','Abbas ibn Firnas',['ibn firnas','abbas ibn firnas','armen firman','first aviator'],
    'Andalusian polymath who made the first recorded attempt at controlled human flight and invented various devices.',{
    def:['Abu\'l-Qasim Abbas ibn Firnas (c. 810\u2013887) was an Andalusian polymath from Ronda (near Cordoba), known for early flight attempt, crystal manufacture, and mechanical inventions.',
         'In 875 CE, at age 65, he reportedly glided for several minutes using a silk-covered wooden frame, making him the first person to attempt controlled flight.'],
    int:['Ibn Firnas is history\'s first "aviator" \u2014 his flight attempt over Cordoba predates Eilmer of Malmesbury\'s and Leonardo da Vinci\'s work by 600 years.',
         'He was a true polymath: astronomer, chemist, musician, inventor, and poet.'],
    ex:['He manufactured colorless crystal glass from raw materials, improving on colored glass techniques.',
         'He invented a water clock, an armillary sphere corrected for planetary positions, and a corrective lens for reading.'],
    form:['His flying machine was a wooden frame covered with silk and actual bird feathers; witnesses reported he flew for a considerable distance before crashing.',
          'He later identified that the failure was due to the lack of a tail mechanism \u2014 an insight into aerodynamic stability.'],
    app:['Ibn Firnas is honored as the first scientific aeronaut; his name adorns a crater on the Moon and a bridge in Cordoba.',
         'His contributions to glassmaking impacted the development of optics and scientific instruments.']},
   ['al_majriti','astronomy','optics','al_jazari']),

  kb('ibn_bajjah','Ibn Bajjah (Avempace)',['ibn bajjah','avempace','ibn bajja','zurara','andalusian philosopher'],
    'Andalusian philosopher, astronomer, and physician who developed a naturalistic philosophy and anticipated Galilean motion.',{
    def:['Abu Bakr Muhammad ibn Yahya ibn al-Sa\'igh ibn Bajjah (c. 1085\u20131138), known in the West as Avempace, was an Andalusian philosopher, astronomer, and physician.',
         'He wrote on physics, psychology, and political philosophy, developing a naturalistic metaphysics that influenced later European thought.'],
    int:['Ibn Bajjah was the first major Andalusian philosopher, establishing a tradition that continued with Ibn Tufayl and Ibn Rushd.',
         'He anticipated Galileo by proposing that the same laws of motion apply to both terrestrial and celestial realms.'],
    ex:['His "Regimen of the Solitary" described the ideal philosopher who achieves intellectual perfection while living in an imperfect society.',
         'He analyzed projectile motion, arguing that a medium\'s resistance, not "antiperistasis," slows projectiles.'],
    form:['He argued that motion in a vacuum would continue indefinitely (anticipating Newton\'s first law).',
          'His critique of Ptolemaic astronomy held that astronomy should describe physical reality, not just save the phenomena.'],
    app:['His ideas on motion and the void influenced later European physics through Averroes\' commentaries.',
         'His concept of intellectual perfection resonated with later European rationalist philosophy.']},
   ['ibn_tufayl','ibn_rushd','philosophy_golden_age','al_farabi']),

  kb('ibn_tufayl','Ibn Tufayl',['ibn tufayl','abu bakar','abuubekr','hayy ibn yaqzan'],
    'Andalusian philosopher and physician whose novel "Hayy ibn Yaqzan" explored the nature of reason and revelation.',{
    def:['Abu Bakr Muhammad ibn Abd al-Malik ibn Muhammad ibn Tufayl al-Qaysi (1105\u20131185), known in the West as Abubacer, was an Andalusian philosopher, physician, and vizier.',
         'His philosophical novel "Hayy ibn Yaqzan" (The Living Son of the Vigilant) tells the story of a feral child who discovers truth through reason alone, independent of society.'],
    int:['Ibn Tufayl\'s novel is a thought experiment in epistemology: can a human, using only natural reason, arrive at the same truths as revealed religion?',
         'It is the world\'s first philosophical novel and a precursor to Robinson Crusoe and Enlightenment rationalism.'],
    ex:['Hayy, growing up alone on a desert island, discovers fire, tools, astronomy, physics, and ultimately God through observation and reason.',
         'When he encounters civilization, he finds that rational truth and revealed religion agree, though religion uses allegory for the masses.'],
    form:['The novel\'s structure mirrors the path of knowledge: empirical observation \u2192 scientific reasoning \u2192 metaphysical contemplation \u2192 mystical union.',
          'Ibn Tufayl\'s work is a response to al-Ghazali\'s critique of philosophy, arguing that reason suffices for truth.'],
    app:['The novel was translated into Latin and European languages, influencing John Locke\'s concept of the tabula rasa and Enlightenment philosophers.',
         'It remains a classic of Arabic literature and philosophy, studied for its profound exploration of reason and faith.']},
   ['ibn_bajjah','ibn_rushd','philosophy_golden_age','al_ghazali'])
];
